#!/usr/bin/env python3
"""Generate the frontend political-disclosure list from the backend JSON.

ONE SOURCE (Ajay 2026-09-20, item 2a). ``backend/political/disclosures.json``
holds the rows. This script writes two files the frontend imports:

  * ``frontend/src/lib/politicalDisclosures.ts``           — the module, every
    export and every semantic preserved from the hand-written 2026-05-28 file.
  * ``frontend/src/lib/politicalDisclosures.generated.json`` — a byte-equal copy
    of the source JSON, so a contract test can assert the TS matches the JSON
    without a build step.

Why: a cron container cannot read TypeScript. Before this, ``political/watch.py``
had no way to know which tickers were already on the list, so every run would
have re-proposed MP and INTC forever.

    python -m scripts.gen_political_ts            # write both files
    python -m scripts.gen_political_ts --check    # exit 1 if either is stale

The generated header says DO NOT EDIT and names this script. Editing the TS by
hand is not wrong so much as pointless — the next run of ``--check`` in the
pre-commit contracts fails, and the next real run overwrites it.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC_JSON = REPO / "backend" / "political" / "disclosures.json"
OUT_TS = REPO / "frontend" / "src" / "lib" / "politicalDisclosures.ts"
OUT_JSON = REPO / "frontend" / "src" / "lib" / "politicalDisclosures.generated.json"

GENERATED_BY = "backend/scripts/gen_political_ts.py"

HEADER = f"""/**
 * politicalDisclosures.ts — GENERATED by {GENERATED_BY} from
 * backend/political/disclosures.json — DO NOT EDIT.
 *
 * Edit the JSON and re-run:  cd backend && python -m scripts.gen_political_ts
 *
 * The list: stocks with disclosed positions held by public officials / their
 * immediate family AND stocks with direct U.S. government involvement (equity
 * stakes, major contracts, eligible-asset designations).
 *
 * Added 2026-05-28 per user request: surface a chip when "Trump or U.S.
 * government investments go into a stock". Moved to the backend JSON
 * 2026-09-20 so the 🏛️ watch cron can read the same rows the chip renders —
 * a cron container cannot import TypeScript, and a second copy of a curated
 * list is a second copy that drifts.
 *
 * ───────────────────────────────────────────────────────────────────
 * IMPORTANT — this is INFORMATIONAL, not a buy or sell signal.
 *
 * Disclosed positions don't predict outcomes. The chip flags context the user
 * wants to be aware of when evaluating a name; it does not imply the
 * disclosure caused performance or that the official's family has private
 * information. Cross-reference with Minervini gates + volume + whales before
 * any allocation decision.
 *
 * Sources (per user 2026-05-28):
 *   1. U.S. Office of Government Ethics public disclosures (OGE.gov)
 *   2. Reputable news-aggregation reporting (NYT, Bloomberg, WSJ)
 *
 * The 🏛️ watch (backend/political/watch.py) NEVER edits this list. It fills a
 * separate candidate collection a human reads on the POTUS tab; promoting a
 * candidate means editing the JSON and re-running this script.
 */
"""

TYPES = """
/** Category of political signal. Multiple categories can apply to one
 *  ticker — e.g. INTC has both family-disclosed AND govt-investment
 *  context, so it renders both chips. */
export type DisclosureCategory =
{category_union};

export type DisclosureEntry = {{
  ticker:    string;
  company:   string;
  sector:    string;
  /** One or more categories. Drives which chip(s) render. */
  categories: DisclosureCategory[];
  /** Disclosed value band when known (e.g. "$1M-$5M"). null when the
   *  source named the position but didn't include a band. */
  disclosureBand?: string | null;
  /** For 'govt_investment' rows ONLY: the holder and the size of the
   *  government's EQUITY position, in the form "<agency> <pct>" (e.g.
   *  "DoD 15%"). Renders on the 🇺🇸 chip so the size is readable without
   *  opening the drill. Added 2026-09-19 — the 2025-26 critical-minerals
   *  wave is the first time the size varies enough to matter; before it,
   *  every govt row was CHIPS-Act-shaped and the chip said enough.
   *
   *  A row without a NAMED agency and a STATED percentage leaves this
   *  null and does not get to imply one. "The administration is weighing
   *  a stake" is not a stake. Enforced by political.disclosures.validate. */
  govtStake?: string | null;
  /** Source note from the original table — appears in the tooltip. */
  notes?: string | null;
  /** When the list-row was last verified or sourced (informational). */
  asOf?: string | null;
  /** ISO date this row was ADDED to the list. Drives the 🆕 highlight so a
   *  name that arrived this week is distinguishable from one that has sat
   *  here since the seed list. null on the 2026-05-28 seed rows. */
  addedOn?: string | null;
}};

/** How long a row keeps its 🆕 highlight after `addedOn`. Fourteen days —
 *  long enough that a name added on a Friday is still flagged the
 *  following weekend, short enough that the highlight means something.
 *  Mirrors political.disclosures.NEW_DISCLOSURE_DAYS. */
export const NEW_DISCLOSURE_DAYS = {new_days};
"""

TAIL = """
const SOURCE_NOTE =
  'Sources: U.S. Office of Government Ethics public disclosures (OGE.gov) + ' +
  'reputable news reporting (NYT, Bloomberg, WSJ). User-curated 2026-05-28. ' +
  'Edit backend/political/disclosures.json and re-run ' +
  'backend/scripts/gen_political_ts.py to update.';

/** Lazy-built lookup map — ticker (uppercase) → entry. */
let _map: Map<string, DisclosureEntry> | null = null;
function getMap(): Map<string, DisclosureEntry> {
  if (_map) return _map;
  _map = new Map();
  for (const e of ENTRIES) _map.set(e.ticker.toUpperCase(), e);
  return _map;
}

export function getPoliticalDisclosure(ticker: string): DisclosureEntry | null {
  if (!ticker) return null;
  return getMap().get(ticker.toUpperCase()) ?? null;
}

/** True when `addedOn` is within NEW_DISCLOSURE_DAYS of `now`.
 *
 *  `now` is injectable so the tests pin a date instead of drifting into a
 *  pass-by-calendar — a 14-day window tested against the real clock goes
 *  green for two weeks and then silently red forever.
 *
 *  A row with no `addedOn` (every seed row) is never new. An unparseable or
 *  FUTURE date is never new either: a typo must not mint a highlight.
 *
 *  Same rule as political.disclosures.is_new on the backend.
 */
export function isNewDisclosure(e: DisclosureEntry | null,
                                now: Date = new Date()): boolean {
  if (!e?.addedOn) return false;
  const added = Date.parse(`${e.addedOn}T00:00:00Z`);
  if (!Number.isFinite(added)) return false;
  const ageDays = (now.getTime() - added) / 86_400_000;
  if (ageDays < 0) return false;
  return ageDays <= NEW_DISCLOSURE_DAYS;
}

/** Convenience — returns one boolean per chip the card should render. */
export function getPoliticalChipFlags(ticker: string, now?: Date): {
  hasPotusFamily:    boolean;
  hasGovtInvestment: boolean;
  hasGovtContractor: boolean;
  isInferred:        boolean;
  /** Added 2026-09-19 — drives the 🆕 highlight. */
  isNew:             boolean;
  entry:             DisclosureEntry | null;
} {
  const e = getPoliticalDisclosure(ticker);
  if (!e) {
    return {
      hasPotusFamily:    false,
      hasGovtInvestment: false,
      hasGovtContractor: false,
      isInferred:        false,
      isNew:             false,
      entry:             null,
    };
  }
  return {
    hasPotusFamily:    e.categories.includes('potus_family'),
    hasGovtInvestment: e.categories.includes('govt_investment'),
    hasGovtContractor: e.categories.includes('govt_contractor'),
    isInferred:        e.categories.includes('inferred'),
    isNew:             isNewDisclosure(e, now),
    entry:             e,
  };
}

/** Every row added within the window, newest first — the "what's new"
 *  read for a page that wants to highlight the arrivals rather than test
 *  one ticker at a time. */
export function recentDisclosures(now: Date = new Date()): DisclosureEntry[] {
  return ENTRIES
    .filter((e) => isNewDisclosure(e, now))
    .sort((a, b) => (b.addedOn || '').localeCompare(a.addedOn || ''));
}

/** The whole list, read-only. Added 2026-09-20 so a board can render every
 *  row without a second fetch; `GET /political/board` serves the same rows
 *  from the same JSON. */
export const POLITICAL_DISCLOSURES: readonly DisclosureEntry[] = ENTRIES;

export const POLITICAL_DISCLOSURE_SOURCE_NOTE = SOURCE_NOTE;
export const POLITICAL_DISCLOSURE_TOTAL_COUNT = ENTRIES.length;
"""


def _ts_string(value: str) -> str:
    """A single-quoted TS string literal. json.dumps gives us correct escaping
    for backslashes, control characters and double quotes; we only have to
    re-quote. Non-ASCII stays literal — the file is UTF-8 and the en-dashes and
    curly apostrophes in the notes are the ones Ajay reads."""
    body = json.dumps(value, ensure_ascii=False)[1:-1].replace("\\\"", "\"")
    return "'" + body.replace("'", "\\'") + "'"


def _ts_value(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(_ts_value(v) for v in value) + "]"
    return _ts_string(str(value))


def render_ts(rows: list[dict], *, categories: tuple[str, ...], new_days: int) -> str:
    from political.disclosures import ROW_KEYS
    union = "\n".join(f"  | {_ts_string(c)}" for c in categories).rstrip()
    parts = [HEADER, TYPES.format(category_union=union, new_days=new_days)]
    body = ["\n/** The rows, generated from backend/political/disclosures.json.",
            " *  To add or remove a ticker edit THAT file and re-run the generator. */",
            "const ENTRIES: DisclosureEntry[] = ["]
    for row in rows:
        fields = ", ".join(f"{k}: {_ts_value(row.get(k))}" for k in ROW_KEYS)
        body.append("  { " + fields + " },")
    body.append("];")
    parts.append("\n".join(body) + "\n")
    parts.append(TAIL)
    return "".join(parts)


def _outputs() -> tuple[str, str]:
    sys.path.insert(0, str(REPO / "backend"))
    from political.disclosures import CATEGORIES, NEW_DISCLOSURE_DAYS, validate
    raw = SRC_JSON.read_text(encoding="utf-8")
    rows = json.loads(raw)
    errs = validate(rows)
    if errs:
        raise SystemExit("disclosures.json is invalid:\n  " + "\n  ".join(errs))
    return render_ts(rows, categories=CATEGORIES, new_days=NEW_DISCLOSURE_DAYS), raw


def _rel(path: Path) -> str:
    """A readable path for the log. A monkeypatched test path can sit outside
    the repo, and a cosmetic ``relative_to`` must never be what fails a run."""
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 when either generated file is stale")
    args = ap.parse_args(argv)
    ts, raw_json = _outputs()
    if args.check:
        stale = []
        if not OUT_TS.exists() or OUT_TS.read_text(encoding="utf-8") != ts:
            stale.append(_rel(OUT_TS))
        if not OUT_JSON.exists() or OUT_JSON.read_text(encoding="utf-8") != raw_json:
            stale.append(_rel(OUT_JSON))
        if stale:
            print("STALE — re-run `python -m scripts.gen_political_ts`:")
            for s in stale:
                print("  " + s)
            return 1
        print("political TS is up to date with the JSON")
        return 0
    OUT_TS.write_text(ts, encoding="utf-8")
    OUT_JSON.write_text(raw_json, encoding="utf-8")
    print(f"wrote {_rel(OUT_TS)} and {_rel(OUT_JSON)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
