"""Curated Hyderabadi/Andhra family recipe DB with metadata.

Each recipe has:
  - id, name, type, protein, tags
  - prep_min, cuisine, url (recipe link, popular Indian food blogs)
  - iron_mg (rough estimate per serving — used for wife's iron-rich rotation)
  - kid_friendly, lunch_next_day, iron_rich, probiotic, citrus, weekend
  - ingredients: list of {item, qty, unit, category} for grocery roll-up

Sources for recipe URLs are reputable Indian food blogs (Hebbar's Kitchen,
Swasthi's Recipes, Vahrehvah, Indian Healthy Recipes, Vismai Food). Where
multiple options exist, picked the one with clearest written instructions
plus video.

The list is intentionally compact (~50 dishes) — enough variety to
rotate through 2-3 weeks without repeats, but small enough to maintain
by hand. Add new ones by appending to RECIPES at the bottom.
"""
from __future__ import annotations

# Type categories (matched by planner per-slot):
#   main_curry         — dinner main, eaten with rice for next-day lunch
#   side_curry         — vegetable side, can stack with main
#   rasam              — pappu charu / aamla charu / sambar (always with dinner)
#   breakfast_adult    — for husband + wife
#   breakfast_kid      — fresh, probiotic-leaning, mild for 3.5y old
#   breakfast_either   — works for both adults and kid
#
# Protein:
#   goat | chicken | fish | egg | paneer | dal | veg


RECIPES: list[dict] = [
    # ─── Goat (mutton) ─────────────────────────────────────────────────────
    {
        "id": "hyderabadi_mutton_curry",
        "name": "Hyderabadi Mutton Curry",
        "type": "main_curry", "protein": "goat",
        "tags": ["meat", "weekend", "rich"], "iron_mg": 3.2, "prep_min": 90,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://hebbarskitchen.com/mutton-curry-recipe-hyderabadi-mutton/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": True,
        "ingredients": [
            {"item": "goat meat (mutton)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 3, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
            {"item": "curd/yogurt", "qty": 0.5, "unit": "cup", "category": "dairy"},
            {"item": "garam masala", "qty": 2, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "id": "mutton_paya",
        "name": "Paya (Goat Trotters Bone Broth)",
        "type": "main_curry", "protein": "goat",
        "tags": ["meat", "weekend", "broth", "warming"], "iron_mg": 4.8, "prep_min": 180,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/mutton-paya",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": True,
        "ingredients": [
            {"item": "goat trotters (paya)", "qty": 6, "unit": "pieces", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
            {"item": "garam masala", "qty": 2, "unit": "tsp", "category": "spices"},
            {"item": "cilantro", "qty": 1, "unit": "bunch", "category": "vegetables"},
        ],
    },
    {
        "id": "mutton_kheema",
        "name": "Mutton Kheema (Minced Goat Curry)",
        "type": "main_curry", "protein": "goat",
        "tags": ["meat", "quick", "kid_friendly"], "iron_mg": 3.5, "prep_min": 50,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://www.vismaifood.com/recipes/mutton-kheema-recipe",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "minced goat", "qty": 500, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "green peas", "qty": 0.5, "unit": "cup", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "hyderabadi_mutton_biryani",
        "name": "Hyderabadi Mutton Biryani (Dum)",
        "type": "main_curry", "protein": "goat",
        "tags": ["meat", "weekend", "feast"], "iron_mg": 4.0, "prep_min": 150,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://hebbarskitchen.com/hyderabadi-mutton-biryani-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": True,
        "ingredients": [
            {"item": "goat meat", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "basmati rice", "qty": 500, "unit": "g", "category": "pantry"},
            {"item": "onion", "qty": 4, "unit": "large", "category": "vegetables"},
            {"item": "curd/yogurt", "qty": 1, "unit": "cup", "category": "dairy"},
            {"item": "mint leaves", "qty": 1, "unit": "bunch", "category": "vegetables"},
            {"item": "saffron", "qty": 1, "unit": "pinch", "category": "spices"},
        ],
    },

    # ─── Chicken ───────────────────────────────────────────────────────────
    {
        "id": "telangana_mamsam_curry",
        "name": "Telangana Mamsam (Goat) Curry — Stone-Pot Style",
        "type": "main_curry", "protein": "goat",
        "tags": ["meat", "telangana", "weekend"], "iron_mg": 3.4, "prep_min": 100,
        "quick": False,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/telangana-mutton-curry",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": True,
        "ingredients": [
            {"item": "goat meat (mutton)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 3, "unit": "large", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
            {"item": "red chili powder", "qty": 1.5, "unit": "tsp", "category": "spices"},
            {"item": "garam masala", "qty": 2, "unit": "tsp", "category": "spices"},
            {"item": "coconut", "qty": 0.25, "unit": "cup grated", "category": "pantry"},
        ],
    },
    {
        "id": "telangana_kodi_pulusu",
        "name": "Telangana Kodi Pulusu (Tangy Chicken Stew)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["meat", "telangana", "tangy"], "iron_mg": 1.9, "prep_min": 55,
        "quick": False,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/kodi-pulusu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "chicken (bone-in)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "telangana_chicken_curry",
        "name": "Telangana Chicken Curry (Dry-ish, Country-Style)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["meat", "telangana"], "iron_mg": 1.7, "prep_min": 50,
        "quick": False,
        "cuisine": "telangana", "url": "https://www.vahrehvah.com/telangana-chicken-fry",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "chicken (bone-in)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "curry leaves", "qty": 2, "unit": "sprigs", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "andhra_chicken_curry",
        "name": "Andhra Chicken Curry (Kodi Kura)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["meat", "spicy"], "iron_mg": 1.8, "prep_min": 50,
        "quick": False,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/andhra-chicken-curry/",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "chicken (bone-in)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "coconut", "qty": 0.25, "unit": "cup grated", "category": "pantry"},
            {"item": "red chili powder", "qty": 1.5, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "id": "hyderabadi_chicken_biryani",
        "name": "Hyderabadi Chicken Biryani (Dum)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["meat", "feast"], "iron_mg": 2.5, "prep_min": 90,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://hebbarskitchen.com/hyderabadi-chicken-biryani/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "chicken", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "basmati rice", "qty": 400, "unit": "g", "category": "pantry"},
            {"item": "onion", "qty": 3, "unit": "large", "category": "vegetables"},
            {"item": "curd/yogurt", "qty": 1, "unit": "cup", "category": "dairy"},
            {"item": "mint leaves", "qty": 1, "unit": "bunch", "category": "vegetables"},
        ],
    },
    {
        "id": "chicken_korma",
        "name": "Chicken Korma (Mild Cream Gravy)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["meat", "kid_friendly", "mild"], "iron_mg": 1.9, "prep_min": 60,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/chicken-korma-recipe",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "chicken", "qty": 600, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "cashews", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "curd/yogurt", "qty": 0.5, "unit": "cup", "category": "dairy"},
            {"item": "cream", "qty": 0.25, "unit": "cup", "category": "dairy"},
        ],
    },
    {
        "id": "chicken_kheema",
        "name": "Chicken Kheema",
        "type": "main_curry", "protein": "chicken",
        "tags": ["meat", "quick", "kid_friendly"], "iron_mg": 2.1, "prep_min": 40,
        "quick": False,
        "cuisine": "hyderabadi", "url": "https://www.indianhealthyrecipes.com/chicken-keema-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "minced chicken", "qty": 500, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "green peas", "qty": 0.5, "unit": "cup", "category": "vegetables"},
        ],
    },

    # ─── Fish ──────────────────────────────────────────────────────────────
    {
        "id": "pomfret_fry",
        "name": "Golden Pomfret Tawa Fry",
        "type": "main_curry", "protein": "fish",
        "tags": ["fish", "quick"], "iron_mg": 1.5, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.vahrehvah.com/fish-fry",
        "kid_friendly": True, "lunch_next_day": False,  # fish loses quality next day
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "golden pomfret", "qty": 4, "unit": "fish", "category": "meat"},
            {"item": "ginger-garlic paste", "qty": 1, "unit": "tbsp", "category": "pantry"},
            {"item": "lemon", "qty": 1, "unit": "whole", "category": "vegetables"},
            {"item": "rice flour", "qty": 2, "unit": "tbsp", "category": "pantry"},
            {"item": "red chili powder", "qty": 1, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "id": "andhra_fish_curry",
        "name": "Andhra Chepala Pulusu (Tamarind Fish Curry)",
        "type": "main_curry", "protein": "fish",
        "tags": ["fish", "spicy", "tangy"], "iron_mg": 1.9, "prep_min": 40,
        "quick": False,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/andhra-fish-curry-chepala-pulusu/",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "fish (pomfret/seer)", "qty": 600, "unit": "g", "category": "meat"},
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "fenugreek seeds", "qty": 0.5, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "id": "shrimp_iguru",
        "name": "Royyala Iguru (Telangana Shrimp Curry)",
        "type": "main_curry", "protein": "fish",
        "tags": ["seafood", "telangana", "occasional"], "iron_mg": 2.4, "prep_min": 35,
        "quick": False,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/royyala-iguru-prawn-curry",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "shrimp (cleaned)", "qty": 500, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "shrimp_pulao",
        "name": "Royyala Pulao (Shrimp Pulao)",
        "type": "main_curry", "protein": "fish",
        "tags": ["seafood", "telangana", "occasional", "rice"], "iron_mg": 2.0, "prep_min": 50,
        "quick": False,
        "cuisine": "telangana", "url": "https://www.vahrehvah.com/prawn-pulao-1",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "shrimp", "qty": 400, "unit": "g", "category": "meat"},
            {"item": "basmati rice", "qty": 2, "unit": "cups", "category": "pantry"},
            {"item": "onion", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "mint leaves", "qty": 1, "unit": "small bunch", "category": "vegetables"},
        ],
    },
    {
        "id": "pomfret_masala",
        "name": "Pomfret Masala Curry",
        "type": "main_curry", "protein": "fish",
        "tags": ["fish"], "iron_mg": 1.6, "prep_min": 35,
        "quick": False,
        "cuisine": "indian", "url": "https://hebbarskitchen.com/fish-curry-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "golden pomfret", "qty": 4, "unit": "fish", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "coconut milk", "qty": 1, "unit": "cup", "category": "pantry"},
        ],
    },

    # ─── Dal / Rasam (always with dinner) ──────────────────────────────────
    {
        "id": "palak_dal",
        "name": "Palak Dal (Spinach Lentils)",
        "type": "side_curry", "protein": "dal",
        "tags": ["dal", "iron", "leafy"], "iron_mg": 5.5, "prep_min": 35,
        "quick": False,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/palakura-pappu-andhra-style/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "spinach (palak)", "qty": 2, "unit": "bunches", "category": "vegetables"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
        ],
    },
    {
        "id": "methi_dal",
        "name": "Methi Dal (Fenugreek Lentils)",
        "type": "side_curry", "protein": "dal",
        "tags": ["dal", "iron", "leafy"], "iron_mg": 4.8, "prep_min": 35,
        "quick": False,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/methi-dal/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "fenugreek leaves (methi)", "qty": 2, "unit": "bunches", "category": "vegetables"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "pappu_charu",
        "name": "Pappu Charu (Andhra Lentil Rasam)",
        "type": "rasam", "protein": "dal",
        "tags": ["dal", "rasam", "light"], "iron_mg": 2.5, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.vismaifood.com/recipes/pappu-charu-recipe",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "toor dal", "qty": 0.5, "unit": "cup", "category": "pantry"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "drumstick", "qty": 1, "unit": "stick", "category": "vegetables"},
        ],
    },
    {
        "id": "aamla_charu",
        "name": "Aamla Charu (Gooseberry Rasam — Iron + Citrus Booster)",
        "type": "rasam", "protein": "dal",
        "tags": ["rasam", "iron", "citrus", "wife"], "iron_mg": 3.2, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.vahrehvah.com/amla-rasam",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "amla (gooseberry)", "qty": 4, "unit": "whole", "category": "vegetables"},
            {"item": "toor dal", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "garlic", "qty": 6, "unit": "cloves", "category": "vegetables"},
            {"item": "curry leaves", "qty": 1, "unit": "sprig", "category": "vegetables"},
        ],
    },
    {
        "id": "tomato_pappu",
        "name": "Tomato Pappu",
        "type": "side_curry", "protein": "dal",
        "tags": ["dal", "tangy"], "iron_mg": 3.8, "prep_min": 30,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/tomato-pappu-recipe-andhra-tomato-dal/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "tomato", "qty": 4, "unit": "medium", "category": "vegetables"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "sambar",
        "name": "Mixed Vegetable Sambar",
        "type": "rasam", "protein": "dal",
        "tags": ["dal", "rasam", "veg"], "iron_mg": 3.0, "prep_min": 40,
        "quick": False,
        "cuisine": "south_indian", "url": "https://hebbarskitchen.com/sambar-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "drumstick", "qty": 2, "unit": "sticks", "category": "vegetables"},
            {"item": "okra (bhindi)", "qty": 8, "unit": "pieces", "category": "vegetables"},
            {"item": "carrot", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
        ],
    },
    {
        "id": "pachi_pulusu",
        "name": "Pachi Pulusu (Telangana Raw Tamarind Charu — No Cooking)",
        "type": "rasam", "protein": "veg",
        "tags": ["telangana", "rasam", "raw", "summer"], "iron_mg": 1.4, "prep_min": 10,
        "quick": True,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/pachi-pulusu-recipe",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "green chili", "qty": 2, "unit": "whole", "category": "vegetables"},
            {"item": "jaggery", "qty": 1, "unit": "tbsp", "category": "pantry"},
            {"item": "cilantro", "qty": 1, "unit": "small bunch", "category": "vegetables"},
        ],
    },
    {
        "id": "majjiga_charu",
        "name": "Majjiga Charu (Buttermilk Rasam — Telangana)",
        "type": "rasam", "protein": "dal",
        "tags": ["telangana", "rasam", "probiotic", "cooling"], "iron_mg": 1.0, "prep_min": 15,
        "quick": True,
        "cuisine": "telangana", "url": "https://www.indianhealthyrecipes.com/majjiga-pulusu-andhra-buttermilk-curry/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "buttermilk", "qty": 3, "unit": "cups", "category": "dairy"},
            {"item": "ginger", "qty": 1, "unit": "inch", "category": "vegetables"},
            {"item": "green chili", "qty": 2, "unit": "whole", "category": "vegetables"},
            {"item": "curry leaves", "qty": 1, "unit": "sprig", "category": "vegetables"},
            {"item": "mustard seeds", "qty": 0.5, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "id": "tomato_charu",
        "name": "Tomato Charu (Telangana Tomato Rasam)",
        "type": "rasam", "protein": "dal",
        "tags": ["telangana", "rasam", "tangy"], "iron_mg": 2.2, "prep_min": 25,
        "quick": True,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/tomato-charu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "tomato", "qty": 4, "unit": "medium", "category": "vegetables"},
            {"item": "toor dal", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "garlic", "qty": 6, "unit": "cloves", "category": "vegetables"},
        ],
    },
    {
        "id": "miriyala_charu",
        "name": "Miriyala Charu (Pepper Rasam)",
        "type": "rasam", "protein": "dal",
        "tags": ["rasam", "spicy", "warming"], "iron_mg": 1.8, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/pepper-rasam-recipe-miriyala-charu/",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
            {"item": "black pepper", "qty": 1, "unit": "tsp", "category": "spices"},
            {"item": "cumin seeds", "qty": 1, "unit": "tsp", "category": "spices"},
            {"item": "garlic", "qty": 6, "unit": "cloves", "category": "vegetables"},
        ],
    },
    {
        "id": "nimmakaya_charu",
        "name": "Nimmakaya Charu (Lemon Rasam — Citrus Boost)",
        "type": "rasam", "protein": "dal",
        "tags": ["rasam", "citrus", "wife"], "iron_mg": 1.6, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/nimmakaya-charu-recipe-lemon-rasam/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "lemon", "qty": 2, "unit": "whole", "category": "vegetables"},
            {"item": "toor dal", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "ginger", "qty": 1, "unit": "inch", "category": "vegetables"},
        ],
    },

    # ─── Hyderabad / Telangana classics ────────────────────────────────────
    # Sourced from Vismai Food (Telugu) + VahChef / Vahrehvah (Sanjay Thumma,
    # the Hyderabadi cooking authority). These are the dishes Hyderabadi
    # families actually eat — not the tourist version.
    {
        "id": "hyderabadi_bagara_baingan",
        "name": "Hyderabadi Bagara Baingan (Peanut-Sesame Stuffed Brinjal)",
        "type": "main_curry", "protein": "veg",
        "tags": ["hyderabadi", "veg", "biryani_side", "vahchef"], "iron_mg": 1.6, "prep_min": 45,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/bagara-baingan",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "quick": False,
        "ingredients": [
            {"item": "small brinjal (eggplant)", "qty": 8, "unit": "pieces", "category": "vegetables"},
            {"item": "peanuts", "qty": 0.5, "unit": "cup", "category": "pantry"},
            {"item": "sesame seeds", "qty": 3, "unit": "tbsp", "category": "spices"},
            {"item": "coconut", "qty": 0.25, "unit": "cup grated", "category": "pantry"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
        ],
    },
    {
        "id": "mirchi_ka_salan",
        "name": "Hyderabadi Mirchi Ka Salan (Biryani's Best Friend)",
        "type": "side_curry", "protein": "veg",
        "tags": ["hyderabadi", "biryani_side", "vahchef"], "iron_mg": 1.4, "prep_min": 35,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/mirchi-ka-salan",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "quick": False,
        "ingredients": [
            {"item": "long green chilies (bhavnagri)", "qty": 10, "unit": "pieces", "category": "vegetables"},
            {"item": "peanuts", "qty": 0.5, "unit": "cup", "category": "pantry"},
            {"item": "sesame seeds", "qty": 2, "unit": "tbsp", "category": "spices"},
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
        ],
    },
    {
        "id": "hyderabadi_khatti_dal",
        "name": "Hyderabadi Khatti Dal (Sour Tamarind Dal)",
        "type": "side_curry", "protein": "dal",
        "tags": ["hyderabadi", "dal", "tangy", "vahchef", "weeknight"], "iron_mg": 3.4, "prep_min": 30,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/khatti-dal",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "garlic", "qty": 8, "unit": "cloves", "category": "vegetables"},
            {"item": "curry leaves", "qty": 2, "unit": "sprigs", "category": "vegetables"},
        ],
    },
    {
        "id": "dum_ka_murgh",
        "name": "Hyderabadi Dum Ka Murgh (Slow-Sealed Chicken)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["hyderabadi", "weekend", "rich", "vahchef"], "iron_mg": 2.4, "prep_min": 75,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/dum-ka-murgh",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": True,
        "quick": False,
        "ingredients": [
            {"item": "chicken (bone-in)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "curd/yogurt", "qty": 1, "unit": "cup", "category": "dairy"},
            {"item": "cashews", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "fried onions (birista)", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "saffron", "qty": 1, "unit": "pinch", "category": "spices"},
        ],
    },
    {
        "id": "gongura_mamsam",
        "name": "Gongura Mamsam (Telangana Goat with Sorrel Leaves)",
        "type": "main_curry", "protein": "goat",
        "tags": ["telangana", "weekend", "iron", "vismai"], "iron_mg": 5.8, "prep_min": 95,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/gongura-mutton",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": True,
        "quick": False,
        "ingredients": [
            {"item": "goat meat (mutton)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "gongura (sorrel) leaves", "qty": 2, "unit": "bunches", "category": "vegetables"},
            {"item": "onion", "qty": 3, "unit": "large", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "talawa_gosht",
        "name": "Hyderabadi Talawa Gosht (Pan-Fried Goat)",
        "type": "main_curry", "protein": "goat",
        "tags": ["hyderabadi", "weekend", "vahchef"], "iron_mg": 3.6, "prep_min": 80,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/talawa-gosht",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": True,
        "quick": False,
        "ingredients": [
            {"item": "goat meat (mutton)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 3, "unit": "large", "category": "vegetables"},
            {"item": "curd/yogurt", "qty": 0.5, "unit": "cup", "category": "dairy"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "bagara_khana",
        "name": "Bagara Khana (Hyderabadi Spiced Rice — Mirchi Salan Side)",
        "type": "main_curry", "protein": "veg",
        "tags": ["hyderabadi", "rice", "quick", "vahchef"], "iron_mg": 1.4, "prep_min": 30,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/bagara-khana",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "basmati rice", "qty": 2, "unit": "cups", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "large", "category": "vegetables"},
            {"item": "mint leaves", "qty": 1, "unit": "small bunch", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "pesara_pappu",
        "name": "Pesara Pappu (Quick Split Mung Dal — Weeknight)",
        "type": "side_curry", "protein": "dal",
        "tags": ["telangana", "dal", "quick", "weeknight"], "iron_mg": 3.6, "prep_min": 25,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/pesara-pappu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "split moong dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "garlic", "qty": 6, "unit": "cloves", "category": "vegetables"},
        ],
    },
    {
        "id": "dosakai_pappu",
        "name": "Dosakai Pappu (Yellow Cucumber Dal — Telangana)",
        "type": "side_curry", "protein": "dal",
        "tags": ["telangana", "dal", "vismai"], "iron_mg": 2.8, "prep_min": 30,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/dosakai-pappu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "dosakai (yellow cucumber)", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "kodi_vepudu",
        "name": "Kodi Vepudu (Andhra/Telangana Chicken Fry — Quick Weeknight)",
        "type": "main_curry", "protein": "chicken",
        "tags": ["telangana", "quick", "weeknight", "vismai"], "iron_mg": 2.0, "prep_min": 35,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/kodi-vepudu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "chicken (boneless)", "qty": 600, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "curry leaves", "qty": 2, "unit": "sprigs", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "hyderabadi_khichdi",
        "name": "Hyderabadi Khichdi (Comfort Rice + Dal, Quick)",
        "type": "main_curry", "protein": "dal",
        "tags": ["hyderabadi", "quick", "comfort", "kid_friendly"], "iron_mg": 3.0, "prep_min": 25,
        "cuisine": "hyderabadi", "url": "https://www.vahrehvah.com/hyderabadi-khichdi",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "rice", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "moong dal", "qty": 0.5, "unit": "cup", "category": "pantry"},
            {"item": "ghee", "qty": 2, "unit": "tbsp", "category": "dairy"},
        ],
    },
    {
        "id": "pulusu_kura",
        "name": "Pulusu Kura (Mixed Veg in Tamarind — Telangana)",
        "type": "side_curry", "protein": "veg",
        "tags": ["telangana", "veg", "tangy"], "iron_mg": 1.8, "prep_min": 35,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/pulusu-kura",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "quick": False,
        "ingredients": [
            {"item": "drumstick", "qty": 2, "unit": "sticks", "category": "vegetables"},
            {"item": "bottle gourd", "qty": 0.5, "unit": "medium", "category": "vegetables"},
            {"item": "okra (bhindi)", "qty": 6, "unit": "pieces", "category": "vegetables"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
        ],
    },
    # ─── Amma Chethi Vanta (Mom's Cooking) classics — authentic, long videos
    # so flagged with `video_long: True` so the UI can warn the cook.
    {
        "id": "ulava_charu",
        "name": "Ulava Charu (Horse Gram Broth — Coastal Andhra/Telangana)",
        "type": "rasam", "protein": "dal",
        "tags": ["telangana", "andhra", "rasam", "slow", "amma_chethi_vanta"],
        "iron_mg": 4.6, "prep_min": 90,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/ulavacharu-recipe-ulava-charu/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": True,
        "quick": False,
        "ingredients": [
            {"item": "horse gram (ulavalu)", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
            {"item": "jaggery", "qty": 2, "unit": "tbsp", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "amma_chethi_chicken_curry",
        "name": "Amma Chethi Vanta — Authentic Telangana Chicken Curry",
        "type": "main_curry", "protein": "chicken",
        "tags": ["telangana", "amma_chethi_vanta", "authentic"], "iron_mg": 2.0, "prep_min": 60,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/kodi-pulusu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": False,
        "ingredients": [
            {"item": "chicken (bone-in)", "qty": 750, "unit": "g", "category": "meat"},
            {"item": "onion", "qty": 3, "unit": "large", "category": "vegetables"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "ginger-garlic paste", "qty": 2, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "kobbari_annam",
        "name": "Kobbari Annam (Coconut Rice — Amma Chethi Vanta style)",
        "type": "main_curry", "protein": "veg",
        "tags": ["telangana", "rice", "amma_chethi_vanta", "kid_friendly", "quick"],
        "iron_mg": 1.4, "prep_min": 25,
        "cuisine": "telangana", "url": "https://www.indianhealthyrecipes.com/coconut-rice-recipe-kobbari-annam/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "rice (cooked)", "qty": 3, "unit": "cups", "category": "pantry"},
            {"item": "coconut", "qty": 1, "unit": "cup grated", "category": "pantry"},
            {"item": "cashews", "qty": 0.25, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "sarva_pindi_pancake",
        "name": "Tapala Chekkalu / Sarva Pindi Lite (Telangana Rice Flour Pancake — adult breakfast)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["telangana", "weeknight", "breakfast", "vismai"], "iron_mg": 1.6, "prep_min": 25,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/sarva-pindi",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "rice flour", "qty": 1.5, "unit": "cups", "category": "pantry"},
            {"item": "chana dal", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "ginger", "qty": 1, "unit": "inch", "category": "vegetables"},
        ],
    },

    # ─── Vegetable curries / sides ─────────────────────────────────────────
    {
        "id": "bhindi_fry",
        "name": "Bhindi (Okra) Fry — Andhra Style",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "side"], "iron_mg": 1.0, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/bendakaya-vepudu-okra-fry/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "okra (bhindi)", "qty": 500, "unit": "g", "category": "vegetables"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "gutti_vankaya",
        "name": "Gutti Vankaya (Andhra Stuffed Brinjal)",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "andhra"], "iron_mg": 1.2, "prep_min": 45,
        "quick": False,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/gutti-vankaya-curry-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "small brinjal (eggplant)", "qty": 8, "unit": "pieces", "category": "vegetables"},
            {"item": "peanuts", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "sesame seeds", "qty": 2, "unit": "tbsp", "category": "spices"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
        ],
    },
    {
        "id": "sorakaya_curry",
        "name": "Sorakaya (Bottle Gourd) Curry",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "light"], "iron_mg": 0.6, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.vismaifood.com/recipes/sorakaya-kura-bottle-gourd-curry-recipe",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "bottle gourd (sorakaya)", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "moong dal", "qty": 0.25, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "anapakaya_pulusu",
        "name": "Anapakaya Pulusu (Bottle Gourd Tamarind Stew)",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "tangy"], "iron_mg": 0.7, "prep_min": 35,
        "quick": False,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/sorakaya-pulusu/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "bottle gourd", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
            {"item": "jaggery", "qty": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "beerakaya_curry",
        "name": "Beerakaya (Ridge Gourd) Curry",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "light"], "iron_mg": 0.5, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/beerakaya-tomato-curry/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "ridge gourd (beerakaya)", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "drumstick_curry",
        "name": "Drumstick Curry (Munakkaya)",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "iron"], "iron_mg": 2.6, "prep_min": 30,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.vismaifood.com/recipes/drumstick-curry",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "drumstick", "qty": 4, "unit": "sticks", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "palak_paneer",
        "name": "Palak Paneer",
        "type": "main_curry", "protein": "paneer",
        "tags": ["veg", "iron", "kid_friendly"], "iron_mg": 4.5, "prep_min": 40,
        "quick": False,
        "cuisine": "north_indian", "url": "https://www.indianhealthyrecipes.com/palak-paneer-recipe-restaurant-style/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "spinach (palak)", "qty": 2, "unit": "bunches", "category": "vegetables"},
            {"item": "paneer", "qty": 250, "unit": "g", "category": "dairy"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "cream", "qty": 0.25, "unit": "cup", "category": "dairy"},
        ],
    },
    {
        "id": "paneer_butter_masala",
        "name": "Paneer Butter Masala",
        "type": "main_curry", "protein": "paneer",
        "tags": ["veg", "rich", "kid_friendly"], "iron_mg": 1.8, "prep_min": 35,
        "quick": False,
        "cuisine": "north_indian", "url": "https://hebbarskitchen.com/paneer-butter-masala-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "paneer", "qty": 250, "unit": "g", "category": "dairy"},
            {"item": "tomato", "qty": 4, "unit": "medium", "category": "vegetables"},
            {"item": "cashews", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "butter", "qty": 2, "unit": "tbsp", "category": "dairy"},
        ],
    },
    {
        "id": "chana_masala",
        "name": "Chana Masala (Chickpea Curry)",
        "type": "main_curry", "protein": "veg",
        "tags": ["veg", "iron", "filling"], "iron_mg": 3.6, "prep_min": 50,
        "quick": False,
        "cuisine": "north_indian", "url": "https://www.indianhealthyrecipes.com/chana-masala-recipe-punjabi-chana-masala/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "chickpeas (kabuli chana)", "qty": 1.5, "unit": "cups", "category": "pantry"},
            {"item": "onion", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "rajma",
        "name": "Rajma (Kidney Beans Curry)",
        "type": "main_curry", "protein": "veg",
        "tags": ["veg", "iron", "filling"], "iron_mg": 4.2, "prep_min": 60,
        "quick": False,
        "cuisine": "north_indian", "url": "https://www.indianhealthyrecipes.com/rajma-recipe-rajma-masala/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "kidney beans (rajma)", "qty": 1.5, "unit": "cups", "category": "pantry"},
            {"item": "onion", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "tomato", "qty": 3, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "aloo_gobi",
        "name": "Aloo Gobi (Potato + Cauliflower)",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "kid_friendly"], "iron_mg": 1.4, "prep_min": 30,
        "quick": True,
        "cuisine": "north_indian", "url": "https://hebbarskitchen.com/aloo-gobi-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "cauliflower", "qty": 1, "unit": "small head", "category": "vegetables"},
            {"item": "potato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "gongura_pappu",
        "name": "Gongura Pappu (Sorrel Leaves Dal — Telangana classic)",
        "type": "side_curry", "protein": "dal",
        "tags": ["telangana", "iron", "tangy"], "iron_mg": 5.0, "prep_min": 35,
        "quick": False,
        "cuisine": "telangana", "url": "https://www.indianhealthyrecipes.com/gongura-pappu-recipe-sorrel-leaves-dal/",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "gongura (sorrel) leaves", "qty": 2, "unit": "bunches", "category": "vegetables"},
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "baby_spinach_pappu",
        "name": "Baby Spinach Pappu (US-Friendly Palak Dal)",
        "type": "side_curry", "protein": "dal",
        "tags": ["iron", "leafy", "easy_us"], "iron_mg": 4.6, "prep_min": 30,
        "quick": True,
        "cuisine": "telangana", "url": "https://www.indianhealthyrecipes.com/palakura-pappu-andhra-style/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "baby spinach (Costco/H-Mart bag)", "qty": 1, "unit": "large bag", "category": "vegetables"},
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "tamarind", "qty": 1, "unit": "small ball", "category": "pantry"},
        ],
    },
    {
        "id": "kale_pappu",
        "name": "Kale Pappu (Iron-Rich Substitute When No Methi)",
        "type": "side_curry", "protein": "dal",
        "tags": ["iron", "leafy", "easy_us"], "iron_mg": 5.4, "prep_min": 30,
        "quick": True,
        "cuisine": "fusion", "url": "https://www.indianhealthyrecipes.com/methi-dal/",
        "kid_friendly": False, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "kale (curly or lacinato)", "qty": 1, "unit": "bunch", "category": "vegetables"},
            {"item": "toor dal", "qty": 1, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "dondakaya_fry",
        "name": "Dondakaya (Tindora) Fry — Telangana",
        "type": "side_curry", "protein": "veg",
        "tags": ["telangana", "veg", "side"], "iron_mg": 0.8, "prep_min": 25,
        "quick": True,
        "cuisine": "telangana", "url": "https://www.indianhealthyrecipes.com/dondakaya-fry-recipe-tindora-fry/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "ivy gourd (dondakaya/tindora)", "qty": 500, "unit": "g", "category": "vegetables"},
            {"item": "peanuts", "qty": 0.25, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "vankaya_pulusu",
        "name": "Vankaya Pulusu (Brinjal Tamarind Stew — Telangana)",
        "type": "side_curry", "protein": "veg",
        "tags": ["telangana", "tangy"], "iron_mg": 1.0, "prep_min": 30,
        "quick": True,
        "cuisine": "telangana", "url": "https://www.vismaifood.com/recipes/vankaya-pulusu",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "brinjal (eggplant)", "qty": 4, "unit": "medium", "category": "vegetables"},
            {"item": "tamarind", "qty": 1, "unit": "lemon-sized ball", "category": "pantry"},
            {"item": "jaggery", "qty": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "cabbage_poriyal",
        "name": "Cabbage Poriyal",
        "type": "side_curry", "protein": "veg",
        "tags": ["veg", "light"], "iron_mg": 0.8, "prep_min": 20,
        "quick": True,
        "cuisine": "south_indian", "url": "https://www.indianhealthyrecipes.com/cabbage-curry-recipe/",
        "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "cabbage", "qty": 0.5, "unit": "head", "category": "vegetables"},
            {"item": "coconut", "qty": 2, "unit": "tbsp grated", "category": "pantry"},
        ],
    },

    # ─── Daily protein add-on (air fryer / pre-marinated / eggs) ──────────
    # User buys pre-marinated meat from the grocery and air-fries it. No
    # recipe video needed — these are 8-20 min "set and forget" cooks.
    # Planner always includes one of these per dinner so there's protein
    # at every meal even when the main is vegetarian.
    {
        "id": "airfry_marinated_chicken",
        "name": "Air-Fryer Marinated Chicken Tikka (Pre-Marinated, 18min)",
        "type": "protein_side", "protein": "chicken",
        "tags": ["air_fryer", "protein_daily", "quick", "weeknight"],
        "iron_mg": 1.5, "prep_min": 18, "quick": True,
        "cuisine": "indian", "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "pre-marinated chicken tikka (Swadeshi Grocery, Frisco)", "qty": 500, "unit": "g", "category": "meat"},
        ],
    },
    {
        "id": "airfry_marinated_mutton_tikka",
        "name": "Air-Fryer Marinated Mutton/Lamb Tikka (Pre-Marinated, 20min)",
        "type": "protein_side", "protein": "goat",
        "tags": ["air_fryer", "protein_daily", "quick", "weeknight"],
        "iron_mg": 3.0, "prep_min": 20, "quick": True,
        "cuisine": "indian", "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "pre-marinated mutton/lamb kabab (Swadeshi Grocery, Frisco)", "qty": 500, "unit": "g", "category": "meat"},
        ],
    },
    {
        "id": "airfry_marinated_fish",
        "name": "Air-Fryer Marinated Fish Tikka (Pre-Marinated, 12min)",
        "type": "protein_side", "protein": "fish",
        "tags": ["air_fryer", "protein_daily", "quick", "weeknight"],
        "iron_mg": 1.2, "prep_min": 12, "quick": True,
        "cuisine": "indian", "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "pre-marinated fish tikka (Swadeshi Grocery, Frisco)", "qty": 400, "unit": "g", "category": "meat"},
        ],
    },
    {
        "id": "airfry_marinated_shrimp",
        "name": "Air-Fryer Marinated Shrimp (Pre-Marinated, 8min)",
        "type": "protein_side", "protein": "fish",
        "tags": ["air_fryer", "protein_daily", "quick", "seafood"],
        "iron_mg": 2.0, "prep_min": 8, "quick": True,
        "cuisine": "indian", "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "pre-marinated shrimp (Swadeshi Grocery, Frisco)", "qty": 400, "unit": "g", "category": "meat"},
        ],
    },
    {
        "id": "airfry_paneer_tikka",
        "name": "Air-Fryer Paneer Tikka (Pre-Marinated, 12min)",
        "type": "protein_side", "protein": "paneer",
        "tags": ["air_fryer", "protein_daily", "quick", "vegetarian"],
        "iron_mg": 1.8, "prep_min": 12, "quick": True,
        "cuisine": "indian", "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "paneer (cubed)", "qty": 250, "unit": "g", "category": "dairy"},
            {"item": "tikka marinade (curd + spices)", "qty": 0.5, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "boiled_eggs",
        "name": "Hard-Boiled Eggs (Quick Daily Protein)",
        "type": "protein_side", "protein": "egg",
        "tags": ["protein_daily", "quick", "husband", "wife"],
        "iron_mg": 1.4, "prep_min": 12, "quick": True,
        "cuisine": "general", "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "eggs", "qty": 6, "unit": "whole", "category": "dairy"},
        ],
    },
    {
        "id": "airfry_egg_muffins",
        "name": "Air-Fryer Egg White Muffins (Spinach + Cheese, 15min)",
        "type": "protein_side", "protein": "egg",
        "tags": ["air_fryer", "protein_daily", "iron", "wife", "husband"],
        "iron_mg": 3.2, "prep_min": 15, "quick": True,
        "cuisine": "general", "kid_friendly": True, "lunch_next_day": True,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "egg whites", "qty": 8, "unit": "whites", "category": "dairy"},
            {"item": "baby spinach", "qty": 1, "unit": "handful", "category": "vegetables"},
            {"item": "shredded cheese", "qty": 0.25, "unit": "cup", "category": "dairy"},
        ],
    },

    # ─── Adult breakfasts ──────────────────────────────────────────────────
    {
        "id": "egg_white_omelette",
        "name": "Egg White Omelette + Multigrain Toast",
        "type": "breakfast_adult", "protein": "egg",
        "tags": ["protein", "husband", "quick"], "iron_mg": 0.5, "prep_min": 12,
        "quick": True,
        "cuisine": "general", "url": "https://www.eatingwell.com/recipe/250146/spinach-egg-white-omelet/",
        "kid_friendly": False, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "egg whites", "qty": 6, "unit": "whites", "category": "dairy"},
            {"item": "spinach", "qty": 1, "unit": "cup", "category": "vegetables"},
            {"item": "multigrain bread", "qty": 4, "unit": "slices", "category": "pantry"},
        ],
    },
    {
        "id": "egg_white_scramble",
        "name": "Spinach + Egg White Scramble (Iron Boost)",
        "type": "breakfast_adult", "protein": "egg",
        "tags": ["protein", "husband", "iron"], "iron_mg": 3.5, "prep_min": 12,
        "quick": True,
        "cuisine": "general", "url": "https://www.indianhealthyrecipes.com/egg-bhurji-recipe-anda-bhurji/",
        "kid_friendly": False, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "egg whites", "qty": 6, "unit": "whites", "category": "dairy"},
            {"item": "spinach", "qty": 2, "unit": "cups", "category": "vegetables"},
            {"item": "onion", "qty": 1, "unit": "small", "category": "vegetables"},
        ],
    },
    {
        "id": "poha",
        "name": "Poha (Flattened Rice — Wife's Favorite)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["wife", "light", "iron"], "iron_mg": 2.0, "prep_min": 20,
        "quick": True,
        "cuisine": "general", "url": "https://www.indianhealthyrecipes.com/poha-recipe-kanda-poha/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": True, "weekend": False,
        "ingredients": [
            {"item": "poha (flattened rice)", "qty": 2, "unit": "cups", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "medium", "category": "vegetables"},
            {"item": "lemon", "qty": 1, "unit": "whole", "category": "vegetables"},
            {"item": "peanuts", "qty": 0.25, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "oats_pudding",
        "name": "Overnight Oats Pudding (Wife)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["wife", "light", "fiber"], "iron_mg": 2.5, "prep_min": 5,
        "quick": True,
        "cuisine": "general", "url": "https://minimalistbaker.com/the-best-overnight-oats/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "rolled oats", "qty": 0.5, "unit": "cup", "category": "pantry"},
            {"item": "milk/yogurt", "qty": 1, "unit": "cup", "category": "dairy"},
            {"item": "berries", "qty": 0.25, "unit": "cup", "category": "vegetables"},
            {"item": "chia seeds", "qty": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "id": "acai_bowl",
        "name": "Açaí Bowl with Granola + Banana",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["wife", "antioxidant"], "iron_mg": 2.2, "prep_min": 8,
        "quick": True,
        "cuisine": "general", "url": "https://www.feastingathome.com/acai-bowls/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "açaí pack (frozen)", "qty": 1, "unit": "pack", "category": "vegetables"},
            {"item": "banana", "qty": 1, "unit": "whole", "category": "vegetables"},
            {"item": "granola", "qty": 0.25, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "upma",
        "name": "Rava Upma",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["light", "south"], "iron_mg": 1.2, "prep_min": 20,
        "quick": True,
        "cuisine": "south_indian", "url": "https://www.indianhealthyrecipes.com/upma-recipe-rava-upma/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "rava (semolina)", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "small", "category": "vegetables"},
            {"item": "ginger", "qty": 1, "unit": "inch", "category": "vegetables"},
        ],
    },
    {
        "id": "pesarattu",
        "name": "Pesarattu (Andhra Green Moong Dosa) + Ginger Chutney",
        "type": "breakfast_adult", "protein": "dal",
        "tags": ["andhra", "iron", "protein"], "iron_mg": 3.5, "prep_min": 25,
        "quick": True,
        "cuisine": "andhra", "url": "https://www.indianhealthyrecipes.com/pesarattu-recipe-pesarattu-dosa/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": True, "citrus": False, "weekend": True,
        "ingredients": [
            {"item": "green moong dal (whole)", "qty": 1.5, "unit": "cups", "category": "pantry"},
            {"item": "ginger", "qty": 2, "unit": "inches", "category": "vegetables"},
            {"item": "green chili", "qty": 2, "unit": "whole", "category": "vegetables"},
        ],
    },
    {
        "id": "methi_paratha",
        "name": "Methi Paratha (Iron-Rich Flatbread)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["iron", "wife"], "iron_mg": 3.8, "prep_min": 30,
        "quick": False,
        "cuisine": "north_indian", "url": "https://www.indianhealthyrecipes.com/methi-paratha-recipe/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": True,
        "ingredients": [
            {"item": "fenugreek leaves (methi)", "qty": 2, "unit": "bunches", "category": "vegetables"},
            {"item": "wheat flour", "qty": 2, "unit": "cups", "category": "pantry"},
        ],
    },
    {
        "id": "phulka_roti",
        "name": "Phulka / Roti (Soft Whole-Wheat Flatbread)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["quick", "weeknight", "bread"], "iron_mg": 1.4, "prep_min": 15,
        "cuisine": "north_indian", "url": "https://www.indianhealthyrecipes.com/phulka-recipe-how-to-make-phulkas/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "wheat flour (atta)", "qty": 2, "unit": "cups", "category": "pantry"},
            {"item": "ghee", "qty": 1, "unit": "tbsp", "category": "dairy"},
        ],
    },
    {
        "id": "tawa_roti_with_curry",
        "name": "Tawa Roti + Quick Veg Curry (15-min Weeknight)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["quick", "weeknight", "bread", "wife"], "iron_mg": 2.2, "prep_min": 20,
        "cuisine": "north_indian", "url": "https://www.indianhealthyrecipes.com/jeera-aloo-recipe/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "quick": True,
        "ingredients": [
            {"item": "wheat flour (atta)", "qty": 2, "unit": "cups", "category": "pantry"},
            {"item": "potato", "qty": 2, "unit": "medium", "category": "vegetables"},
            {"item": "cumin seeds", "qty": 0.5, "unit": "tsp", "category": "spices"},
        ],
    },
    {
        "id": "vermicelli_upma",
        "name": "Vermicelli Upma (Semiya)",
        "type": "breakfast_adult", "protein": "veg",
        "tags": ["light", "quick"], "iron_mg": 1.0, "prep_min": 18,
        "quick": True,
        "cuisine": "south_indian", "url": "https://www.indianhealthyrecipes.com/semiya-upma-recipe/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "vermicelli (semiya)", "qty": 1.5, "unit": "cups", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "small", "category": "vegetables"},
        ],
    },

    # ─── Kid breakfasts (probiotic, fresh, mild) ───────────────────────────
    {
        "id": "mini_idli",
        "name": "Mini Idlis with Ghee + Coconut Chutney",
        "type": "breakfast_either", "protein": "veg",
        "tags": ["kid", "probiotic", "soft"], "iron_mg": 1.0, "prep_min": 20,
        "quick": True,
        "cuisine": "south_indian", "url": "https://www.indianhealthyrecipes.com/mini-idli-recipe-podi-idli/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "idli batter", "qty": 1, "unit": "small box", "category": "pantry"},
            {"item": "ghee", "qty": 2, "unit": "tbsp", "category": "dairy"},
            {"item": "coconut", "qty": 0.5, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "set_dosa",
        "name": "Set Dosa with Tomato Chutney",
        "type": "breakfast_either", "protein": "veg",
        "tags": ["kid", "probiotic"], "iron_mg": 1.1, "prep_min": 18,
        "quick": True,
        "cuisine": "south_indian", "url": "https://hebbarskitchen.com/set-dosa-recipe-soft-set-dose/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "dosa batter", "qty": 1, "unit": "small box", "category": "pantry"},
            {"item": "tomato", "qty": 2, "unit": "medium", "category": "vegetables"},
        ],
    },
    {
        "id": "rava_idli",
        "name": "Rava Idli (Quick Semolina Idli)",
        "type": "breakfast_either", "protein": "veg",
        "tags": ["kid", "quick"], "iron_mg": 0.9, "prep_min": 25,
        "quick": True,
        "cuisine": "south_indian", "url": "https://www.indianhealthyrecipes.com/rava-idli-recipe/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "rava (semolina)", "qty": 1, "unit": "cup", "category": "pantry"},
            {"item": "yogurt", "qty": 0.5, "unit": "cup", "category": "dairy"},
        ],
    },
    {
        "id": "uttapam",
        "name": "Mini Uttapam with Veggies",
        "type": "breakfast_either", "protein": "veg",
        "tags": ["kid", "probiotic"], "iron_mg": 1.3, "prep_min": 20,
        "quick": True,
        "cuisine": "south_indian", "url": "https://hebbarskitchen.com/uttapam-recipe-onion-tomato/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "dosa batter", "qty": 1, "unit": "small box", "category": "pantry"},
            {"item": "onion", "qty": 1, "unit": "small", "category": "vegetables"},
            {"item": "tomato", "qty": 1, "unit": "small", "category": "vegetables"},
        ],
    },
    {
        "id": "plain_dosa",
        "name": "Plain Crispy Dosa + Coconut Chutney + Sambar",
        "type": "breakfast_either", "protein": "veg",
        "tags": ["kid", "probiotic", "classic"], "iron_mg": 1.4, "prep_min": 15,
        "quick": True,
        "cuisine": "south_indian", "url": "https://www.indianhealthyrecipes.com/dosa-recipe-how-to-make-dosa-batter/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": False, "probiotic": True, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "dosa batter", "qty": 1, "unit": "small box", "category": "pantry"},
            {"item": "coconut", "qty": 0.5, "unit": "cup", "category": "pantry"},
        ],
    },
    {
        "id": "banana_oats_porridge",
        "name": "Banana + Oats Porridge (Toddler-Soft)",
        "type": "breakfast_kid", "protein": "veg",
        "tags": ["kid", "soft"], "iron_mg": 1.6, "prep_min": 10,
        "quick": True,
        "cuisine": "general", "url": "https://www.indianhealthyrecipes.com/oats-porridge-recipe-baby-toddlers/",
        "kid_friendly": True, "lunch_next_day": False,
        "iron_rich": True, "probiotic": False, "citrus": False, "weekend": False,
        "ingredients": [
            {"item": "rolled oats", "qty": 0.25, "unit": "cup", "category": "pantry"},
            {"item": "banana", "qty": 1, "unit": "whole", "category": "vegetables"},
            {"item": "milk", "qty": 1, "unit": "cup", "category": "dairy"},
        ],
    },
]


def by_id(rid: str) -> dict | None:
    for r in RECIPES:
        if r.get("id") == rid:
            return r
    return None


def by_type(t: str) -> list[dict]:
    return [r for r in RECIPES if r.get("type") == t]


def filter_recipes(*, t: str | None = None, protein: str | None = None,
                   iron_rich: bool | None = None,
                   probiotic: bool | None = None,
                   exclude_ids: list[str] | None = None,
                   weekend: bool | None = None,
                   quick_only: bool = False,
                   max_prep_min: int | None = None) -> list[dict]:
    out = list(RECIPES)
    if t:
        out = [r for r in out if r.get("type") == t]
    if protein:
        out = [r for r in out if r.get("protein") == protein]
    if iron_rich is not None:
        out = [r for r in out if bool(r.get("iron_rich")) == iron_rich]
    if probiotic is not None:
        out = [r for r in out if bool(r.get("probiotic")) == probiotic]
    if weekend is not None:
        out = [r for r in out if bool(r.get("weekend")) == weekend]
    # Quick filter — drops anything labelled labor-intensive (rolling, kneading,
    # multi-hour braises like paya). Prep_min alone isn't enough since methi
    # paratha is 30min but heavy effort.
    if quick_only:
        out = [r for r in out if r.get("quick")]
    if max_prep_min is not None:
        out = [r for r in out if (r.get("prep_min") or 999) <= max_prep_min]
    if exclude_ids:
        ex = set(exclude_ids)
        out = [r for r in out if r.get("id") not in ex]
    return out
