/* newFeatures — registry of recently-shipped features.
 *
 * Ajay 2026-06-18: "whenever we push a new feature, add a visual highlight, and
 * until I view it for the first time log it to analytics."
 *
 * HOW TO USE WHEN YOU SHIP A FEATURE: add one entry below. It then shows a ✨ NEW
 * highlight (nav badge for `route`, and/or an in-place <NewBadge id="..."/>) until
 * the user first views it; impressions + the first view are logged to analytics
 * (see useNewFeatures + /features/* endpoints). Entries older than
 * NEW_WINDOW_DAYS stop highlighting automatically — leave them or prune.
 */
export type NewFeature = {
  /** Stable unique id — also the analytics key. Kebab-case. */
  id: string;
  /** Human label for the what's-new list / tooltip. */
  label: string;
  /** ISO date (YYYY-MM-DD) the feature shipped. */
  addedAt: string;
  /** Page the feature lives on. Visiting it clears the highlight. Omit for
   *  features not tied to a single route (cleared via <NewBadge> interaction). */
  route?: string;
};

export const NEW_FEATURES: NewFeature[] = [
  { id: 'iv-badge', label: '🌡️ IV badge on every page — implied volatility sits right beside the Market Gauge in the nav (compact on the phone bar): the VIX level, the day change (▲ / ▼), the regime word (Calm < 15 · Normal < 20 · Elevated < 30 · Stress) and where today sits in the last 252 sessions ("5th pct"); hover for the term structure (9D/30D, 30D/3M contango / backwardation), VVIX and the one-line read. Click it for the full IV card on the Market Gauge page. Refreshes every 3 minutes; a regime read, not a forecast', addedAt: '2026-09-06', route: '/market-gauge' },
  { id: 'quick-bounce-tab', label: '🪃 Quick Bounce tab on Chart Maps — the names that historically turned at a demand band the SAME DAY (close 3%+ / one ATR off the low within the first three touch days) or gapped up 2%+ the next morning, measured across the whole universe on two years of daily bars with bands recomputed on prior bars only; listed while they sit inside a proven demand band or within 5% above it with 5%+ room to the first proven lid, nearest first. Every rate sits next to the name\'s own any-day base rate and the study\'s persistence check is printed under the board. Paper Auto-Pilot journals a demand-zone entry on one of these names as the quick_bounce lane and flattens it at 15:55 ET (day-trade variant)', addedAt: '2026-09-06', route: '/chart-maps?tab=quick_bounce' },
  { id: 'proven-lids', label: '🧱 Proven lids only — the room read behind your alerts, the paper lanes, the Portfolio 🎯 table and the board plan now skips a ceiling that is not real structure (fewer than 2 touches or strength under 40) and measures to the next PROVEN band. The KLAC lesson: a 1-touch shelf sitting on the demand band read "in band" for two days and blocked the push and the paper buy before the +7% gap; boards still list every band', addedAt: '2026-09-06', route: '/alerts' },
  { id: 'push-plan-line', label: '🧲🪃 The plan inside the push — demand and bounce alerts now end with "buy $lo–hi · stop $x (0.5% under the floor, y% risk) · target $t (nR)": the same stop the paper lane places and the first proven lid as the target, so the phone tells you what to do, not only what happened', addedAt: '2026-09-06', route: '/alerts' },
  { id: 'options-put-spread', label: '🎛️ Options lane sells rich premium — when the chosen call\'s IV is ≥ 45% the lane now SELLS a defined-risk put spread under the band floor (short put at the highest strike under the floor, long put ~5% lower, credit ≥ 15% of the width, one net-credit package, never a naked put), buys it back at ≤ 25% of the credit or on the same underlying exits; no liquid put spread → bull call spread → long call. The tab shows "$1.90 cr" for credits and the journal measures gains on the $ at risk', addedAt: '2026-09-06', route: '/trading?view=options' },
  { id: 'autopilot-options-lane', label: '🎛️ Options tab on Auto-Pilot — a paper OPTIONS lane on the same demand-zone touch your alerts fire on (≥ 5% room to the first band overhead, print ≤ 1% above the band): one long call a day struck at or under the band top with 0.55–0.75 delta (a bull call spread when IV ≥ 45%), 28–60 days out, no earnings inside the window, premium at risk capped at 1% of equity / $1,500. Exits read the UNDERLYING, never the premium — under the band floor, at the supply target, ≤ 7 DTE or 2 days before earnings. The tab carries the switch, open contracts with strike / delta / IV / stop / target, today\'s attempts, closed trades with realized $, a Close-now button, and the lane\'s own journal; the Journal\'s by-lane table gets a 🎛️ Options row', addedAt: '2026-09-06', route: '/trading?view=options' },
  { id: 'global-search', label: '🔍 Global search — ⌘K / Ctrl K (or "/") opens a palette over every page in your menu, tabs included: "notification" brings up Notifications AND the Alerts page, "in demand" lands on Supply / Demand or Chart Maps ▸ Demand zones, a typo like "chrtmp" still finds Chart Maps; ↑↓ then Enter to jump. The 🔍 pill sits by the bell on desktop and by the scan chip on the phone', addedAt: '2026-09-06' },
  { id: 'board-rules-info', label: 'ℹ️ Rules pill on every board — Back in Demand, Chart Maps (Back in Demand / Deep Demand / Catalysts), the Alerts page, the Auto-Pilot positions table and the SEPA 🪃 chip each open a short panel listing that board\'s stock picks, stops & targets and alert rules with the live percentages, served by the backend next to the constants themselves (GET /supply-demand/rules) — a changed threshold can never read stale here', addedAt: '2026-09-06', route: '/supply-demand' },
  { id: 'autopilot-exit-queue', label: '⏳ Queued exits on Auto-Pilot — press Exit outside market hours and Alpaca refuses the close (the shares stay held for the cancelled bracket until the next session); the engine now queues the exit, retries every minute, tracks the sell until it fills at the open and journals it with the fill price and your reason. The Stop-status cell reads "⏳ Exit queued", an Unqueue button takes it back, and one line under the table lists everything queued for the open', addedAt: '2026-09-05', route: '/trading' },
  { id: 'autopilot-three-lanes', label: '🧭 Paper Auto-Pilot now has three entry lanes — 📈 Minervini (the book gates, unchanged), 🧲 demand zone / 🚀 breakout (the zone-edge signals under your alert rules) and 🗞️ catalyst (Catalysts-board names clearing the ≥ 5% room floor; its own ON/OFF switch, default OFF). Every trade card wears its lane chip, the Journal opens with a per-lane record (n / open / closed / win % / avg R / expectancy / realized $) — paper account, small n until ~2 weeks of fills', addedAt: '2026-09-05', route: '/trading' },
  { id: 'demand-room-floor', label: '🧱 Back in Demand applies the phone\'s room floor — a name needs ≥ 5% from the live print to the first unbroken band overhead (the alert gate) or it is hidden and counted; "any room" shows it flagged ⛔ into supply. The plan\'s target is now the first band above the PRINT, so a TRU (0.3% under a supply band sitting inside its demand zone, R:R 0.09 from the print) fails on its own', addedAt: '2026-09-05', route: '/supply-demand' },
  { id: 'chart-maps-room-floor', label: '🧱 Chart Maps → Back in Demand and Deep Demand hide tiles with < 5% room to the first band overhead on the live print (same floor as your alerts), say how many they hid, and each tile carries a "room" stat ("+12.4% → 84.10" or "open sky"); the Room ≥ 5% / Any room switch sits beside the phase toggle', addedAt: '2026-09-05', route: '/chart-maps?tab=zones' },
  { id: 'alerts-page', label: '🔔 Alerts page — what actually pushed to your phone, in ET, with the full body of every push (the lock screen clips it), filtered by kind / day / ticker, and a status strip per zone pass saying when it last ran and how many names the phone gate skipped (room < 5% to the first band overhead, > 1% above the demand band, cap). The Demand board is a different list by design (closed-bar scan, full universe, R:R floor) — this page is the phone\'s own log', addedAt: '2026-09-05', route: '/alerts' },
  { id: 'alerted-today-chips', label: '🔔 "alerted 10:42 ET" chips on Back in Demand and the zone-edge board — a row wearing one is on BOTH lists (the board and your phone) today; tap it for the full push on the Alerts page. Rows without it are the board\'s business only', addedAt: '2026-09-05', route: '/supply-demand' },
  { id: 'catalysts-in-chart-maps', label: '\u{1F5DE}️ Catalysts moved into Chart Maps (tab right after Overnight — both are movers boards); /catalysts links and push taps land there with their sub-tab. Cards now lead with room to the first supply band overhead: open sky first, then the biggest gap (the EOSE / CLYM shape), and 🪃 flags names bouncing off a demand band — a configured price-structure read, not advice', addedAt: '2026-09-05', route: '/chart-maps?tab=catalysts' },
  { id: 'sepa-bounce-demand-filter', label: '🪃 SEPA filter → 📐 Zones → Bouncing off Demand: keep only names whose session low touched a demand band or a broken-supply shelf in the last 5 sessions and are now 3% / one ATR above it (the zone-bounce floors). A Supply & Demand overlay, not a book gate; the line under the bar says how much of the list has a zone read yet', addedAt: '2026-09-05', route: '/sepa' },
  { id: 'demand-bounce-room-sort', label: '🪃 Back in Demand now sorts bouncing-off-demand names first, then the biggest gap to the first supply band overhead (open sky leads); each row carries the bounce and the room; R:R is one click away in the sort menu and its floor still applies', addedAt: '2026-09-05', route: '/supply-demand' },
  { id: 'ict-chart-maps-tab', label: '🧭 Chart Maps → ICT (took the Into Supply slot): daily swing points and fair value gaps set the key levels, the 60-minute engine wakes only when a level is tapped and looks for the manipulation (a wick through the low that fails to close through it), the opposite displacement that leaves a new gap, the market structure shift and the inverted-FVG entry — with stop under the manipulation and the next daily swing as the target', addedAt: '2026-09-03', route: '/chart-maps?tab=ict' },
  { id: 'trade-autopsies', label: '🔬 Failed-trade autopsies — every losing Auto-Pilot trade (zone-edge, Minervini or manual) is classified with numbers within a tick: stop clamped by the book, shakeout (reclaimed within 2 sessions), band failed, market down, chased, no follow-through — plus a feedback line, on the Trading page and GET /trading/autopsies', addedAt: '2026-09-03', route: '/trading' },
  { id: 'zone-edge-autopilot-race', label: '⏱️ Paper Auto-Pilot now trades the zone-edge signals — demand arrivals and breakouts through the last supply band, stop 0.5% under the band, max 4 a day — and the Trading page keeps an execution race: the minute the signal appeared vs the engine’s order and fill vs the first time you opened the ticker and your own logged fill, with the median lags and the price gap', addedAt: '2026-09-03', route: '/trading' },
  { id: 'zone-edge-board', label: '🚀 Zone edge — the Demand board (SEPA → Supply / Demand) and Chart Maps → Deep Demand now open with the names within 1% of breaking their LAST supply band toward new highs, plus (Demand board) names within 1% above a demand band — refreshed every minute with a 30-minute distance sparkline. Both page your phone once per band per day (🚀 Breaking resistance, 🧲 demand alert)', addedAt: '2026-09-03', route: '/sepa' },
  { id: 'push-self-heal', label: '🔔 Phone alerts heal themselves — if your device’s push registration expires or the server drops it (that is what silenced your phone on Sep 2), the app re-registers it on the next open and the service worker re-subscribes on rotation. Nothing to toggle', addedAt: '2026-09-03', route: '/notifications' },
  { id: 'sepa-default-supply-tab', label: '🧭 Every SEPA click now opens on the Supply / Demand tab — scanner cards, leaderboards, search, Chart Maps tiles, Back in Demand rows, push taps; the 2026-08-17 Setup deep links follow. Purposed chips (insider, fundamentals, tape, analysis, options) keep their tab', addedAt: '2026-09-03', route: '/sepa' },
  { id: 'demand-proximity-order', label: '📍 Deep Demand and the approaching boards now rank closest-to-the-level first (live price), with money flow (CMF) breaking ties inside a 0.5% distance bucket — no more 2.5%-out name on top of 50 in-band names because its CMF was hotter. Back in Demand keeps reward:risk first (the only cohort with measured positive expectancy)', addedAt: '2026-09-03', route: '/chart-maps' },
  { id: 'zone-bounce-alerts', label: '🪃 Demand-level bounce alerts — a $1B+ name whose day low touched a demand band or a broken-supply shelf (old resistance now support, like NTAP’s $162–168 on Sep 3) and is already 3%+ off the low pages you with the time the low printed and the room to the next supply band (with the R multiple): strong bounces individually, the rest as one digest per 5-min check. Bands with a single touch count — the demand board never saw NTAP because it wants 2+ touches and scores the close, not the low. Mute at Notifications', addedAt: '2026-09-03', route: '/notifications' },
  { id: 'demand-bounce-gate', label: '🧹 Chart Maps demand boards drop names that already bounced 7%+ off the band — zones (reached / approaching / order block) and Deep Demand read the LIVE print, so a 10:00 touch that ran by lunch is gone by the next open of the tab; the count hidden is spelled out under the board', addedAt: '2026-09-03', route: '/chart-maps' },
  { id: 'live-bar-overlay', label: '⏱️ Supply/Demand tab, price-zones and chart tiles now include TODAY’s live bar — nearest support / resistance, the verdict and the chart read the session in progress instead of yesterday’s close (CHPT read “1.4% below support” while the tape was +76%)', addedAt: '2026-09-03', route: '/sepa' },
  { id: 'demand-zone-alerts', label: '🧲 Demand-zone alerts — your phone pages the day a $1B+ name from the demand board arrives inside or within 1% of a tested demand band (once per band per day; names already sitting in a band stay on the board, not your phone), plus one digest per 5-min check of names 1–3% above a band and falling. Gabbar-level names now also get a “nearing” push at 3% above a band while falling, not just the 1% touch. Mute either kind at Notifications', addedAt: '2026-09-03', route: '/notifications' },
  { id: 'portfolio-supply-watch', label: '\u{1F3AF} Sell side on the Portfolio page — every holding now shows its next supply / overhead band with the room left in % and $, ATR-days, and support below (table on top + a line on each card); alerts ⚠️ within 2% then 🎯 in the band, once per band per day, pre/after-market included', addedAt: '2026-09-02', route: '/portfolio' },
  { id: 'signals-tab-holdings', label: '\u{1F4CA} Chart Maps → Signals now includes your portfolio by default — every holding rides the signal board alongside your watchlist', addedAt: '2026-09-02', route: '/chart-maps?tab=signals' },
  { id: 'promo-cap-floor', label: '\u{1F4B0} Promo board hides names under $700M (was $1B for an afternoon) by default (toggle above the tables; unknown caps stay and say \u201ccap n/a\u201d) and shows each name\u2019s market cap under its symbol', addedAt: '2026-09-03', route: '/chart-maps?tab=catalysts&sub=promo' },
  { id: 'supply-sell-signal', label: '\u{1F534} SELL SIGNAL \u2014 when a holding reaches its supply band the Portfolio chip and the phone alert now say it in the first word, not just \u201cin supply\u201d', addedAt: '2026-09-03', route: '/portfolio' },
  { id: 'promo-five-tells-sort', label: '\u{1F9ED} Promo board: the ⚡ live table and the board tables now share one column set (session, last, tag dates, room, tape…) plus five new tells per name — Russell add (with the in-index date), Sales (Bonde YoY read), Catalyst (48h news verdict + top headline), latest 8-K with item codes, and a 30-day SEC filings roll-up — and every column header click-sorts', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts&sub=promo' },
  { id: 'russell-add-dates', label: '\u{1F4C6} Russell watch shows WHEN each candidate would go in — the in-index date per row (Sep 21 IPO add vs Dec 14 reconstitution, from FTSE’s published 2026 calendar: rank day Oct 30, preliminary lists Nov 13), a flag once FTSE’s list is already out, and how long each name has been on the list', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts' },
  { id: 'promo-sticky-headers', label: '\u{1F4CC} Promo board column headers stay put while you scroll a long table and release at its end — on the phone they sit just under the sticky nav', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts&sub=promo' },
  { id: 'promo-board-room-links', label: '\u{1F3AF} Promo board: every row now shows room to run (% to the first band overhead, same read as the Portfolio sell side), an inline mini tape of the price since the tag (marker = first post, colored by the before / mid-run / after read — click for the full tape), StockTwits + SEPA links that land on the Supply / Demand tab (now defaulting to 6 months), rows sorted by the latest announcement, and 8 measured early-caller accounts added to the roster as radar-only', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts&sub=promo' },
  { id: 'session-price-header', label: '\u{1F319} Ticker header shows the regular close with its day change AND the pre/after-market print vs the close — no more one blended number after the bell', addedAt: '2026-09-02', route: '/sepa' },
  { id: 'promo-tag-tape', label: '\u{1F4C8} Promo tag tape — click 📈 on any tagged name for the 5-min price path around the post (pre/post market shaded), a marker at every tag, and a read: posted BEFORE the move, mid-run, or after it', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts&sub=promo' },
  { id: 'promo-board-live-stamps', label: '\u{1F550} Promo board goes live — every tagged row shows WHEN it was tagged (ET date/time), today’s live move, and a live since-tag %, with the sweep now every 10 min', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts&sub=promo' },
  { id: 'promo-live-movers', label: '\u26A1 Promo Circuit goes live — every tagged name priced now (pre/post market), sorted by today’s move, refreshing every 30s, with a 🎪 phone alert on any ±8% mover', addedAt: '2026-09-02', route: '/chart-maps?tab=catalysts' },
  { id: 'support-live-overnight', label: '\u{1F4E1} Live chart on the Support tab — a “5 min · live · pre/post market” view that draws the overnight tape (shaded) against the same demand/supply levels, refreshes every 30s while the extended session is open, and says in one line where price bounced overnight', addedAt: '2026-09-02', route: '/chart-maps?tab=support&tf=5m_live&window=6m' },
  { id: 'promo-circuit-watch', label: '\u{1F3AA} Promo-circuit watch — the pump/alert accounts caught seeding the 8/31–9/1 movers are now tracked: fresh tags show as a SEEDING watchlist on the Catalysts page (with 13D/G owner-stake and shelf-filing EDGAR tells), and an S/A-tier tag docks −15 from a prediction’s conviction score — the tag IS the promotion, never a buy signal', addedAt: '2026-09-01', route: '/chart-maps?tab=catalysts' },
  { id: 'ipo-age-real-listing-date', label: '\u{1F4C5} Real IPO dates — the candidate page’s IPO line no longer mistakes the price cache’s 2-year edge for a listing (SAIC showed “recent IPO ✓” at 12 years old); it now pulls the true listing date from the profile provider and says nothing when it can’t know', addedAt: '2026-08-31' },
  { id: 'in-orderblock-2x2', label: '\u25C9 In the order block + phase lens everywhere \u2014 Back in Demand is a 2\u00D72 (reached/approaching \u00D7 band/order-block; reached+block = first touch happening now, youngest first), and Under Value + Gabbar gain an All / reached / approaching lens on their own levels', addedAt: '2026-08-31', route: '/chart-maps?tab=zones&target=order_block' },
  { id: 'approaching-order-blocks', label: '\u{1F7EA} Approaching \u2192 Order block \u2014 the Approaching view can now target fresh SMC order blocks (last down candle before a \u22651.2\u00D7ATR impulse, never yet revisited, \u226490 bars old) instead of demand bands \u2014 block drawn in purple with its own entry/stop/target', addedAt: '2026-08-31', route: '/chart-maps?tab=zones&phase=approaching&target=order_block' },
  { id: 'hot-sectors-strip', label: '\u{1F525} Hot sectors \u2014 money in / money out over the last 21 sessions, now as sector \u00D7 cap-tier cohorts (Healthcare small caps, Tech large caps \u2026 32 groups, median member vs RSP), pinned above Chart Maps and on the Market Gauge', addedAt: '2026-08-31', route: '/chart-maps' },
  { id: 'phase-toggle-approaching', label: '\u{1F3AF} Reaching vs already reached \u2014 Back in Demand and Deep Demand now toggle between names bouncing IN their band and names still ABOVE it, close, and falling toward it (closest first, same quality gates, knife guard on) \u2014 set the order before the arrival', addedAt: '2026-08-31', route: '/chart-maps?tab=zones&phase=approaching' },
  { id: 'session-board', label: '\u{1F551} Session tab \u2014 after the open, every name on Back in Demand + Deep Demand re-read on intraday bars: bullish/bearish mood, the opening range (which says \u201Cforming\u201D until its window fills), fair-value gaps left by THIS session, and complete Smart-Money sequences \u2014 filtered to the ones sitting at their daily band', addedAt: '2026-08-31', route: '/chart-maps?tab=session' },
  { id: 'buy-band-1r-ceiling', label: '\u{1F3AF} Buy bands now stop where the trade does \u2014 the zone card quoted a whole band but measured R:R at spot only; it now quotes the slice that still pays 1R (QBTS: $16.92\u2013$17.41 was really $16.92\u2013$17.05). Also fixed: the setup scanners\u2019 sit-out-bear-markets gate had never once fired', addedAt: '2026-08-31', route: '/chart-maps' },
  { id: 'ticker-support-5y',    label: '5-year zoom + levels panel on the ticker page',           addedAt: '2026-08-25', route: '/sepa' },
  { id: 'topping-shorts-tab',   label: 'S3 Topping · Shorts tab — book-cited distribution reads', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'scan-health',          label: 'Scan health — every scan audited, counted in the nav', addedAt: '2026-08-25', route: '/health' },
  { id: 'deep-demand-tab',      label: 'Deep Demand tab — 2nd-level arrivals, Bonde sales gate', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'zones-cheetah-rank-full-universe', label: 'Demand zones: 🐆 cheetah composite rank (flow × float velocity × R:R) + ONE full-universe scan (~1,750 names), theme picker retired', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'smc-setups', label: '\u{1F3AF} Smart Money setups \u2014 liquidity sweep \u2192 BOS/CHoCH \u2192 order block \u2192 FVG, graded, with aggressive and conservative entries (and a warning when a stop sits inside the noise)', addedAt: '2026-08-29', route: '/chart-maps?tab=support' },
  { id: 'mood-buy-signal', label: '\u{1F9ED} Market mood + BUY/SELL signal on any ticker you search \u2014 15-min & hourly sentiment score with entry, stop and R, computed on closed bars (never repaints); a monitor watches your holdings every 15 min and scores every signal forward', addedAt: '2026-08-29', route: '/chart-maps?tab=support' },
  { id: 'timeframe-orb-fvg', label: '\u{1F551} Timeframe dropdown on Support + zone drill-ins \u2014 read levels on Daily / 1-hour / 15-min bars, with fair-value gaps, the opening range, computed entry+stop per band, and bullish patterns (cup & handle, inverse H&S, flat top)', addedAt: '2026-08-29', route: '/chart-maps?tab=support' },
  { id: 'desk-report', label: '\u{1F9E0} Desk \u2014 daily 8:40am pre-market report: regime verdict, scored book with entries/stops/sizing, cut list, and yesterday\u2019s ideas graded', addedAt: '2026-08-28', route: '/desk' },
  { id: 'undervalue-tab', label: '\ud83d\udc8e Under Value tab \u2014 explosive sales priced below their growth (PSG \u2264 0.15), with supply/demand zones per name', addedAt: '2026-08-28', route: '/chart-maps' },
  { id: 'smallcap-traction-themes', label: '\ud83c\udf31 27 traction small/mid caps join the universe \u2014 LPTH, INDI, ONDS, RCAT, UUUU, AMBA \u2026 + two new theme chips: \ud83c\udf96 Defense and \u26cf Rare earth', addedAt: '2026-08-28', route: '/chart-maps' },
  { id: 'demand-pinned-etf-roster', label: '\ud83e\udd47 34 pinned ETFs in the demand-zone scan \u2014 GLD/SLV, SPY/QQQ/TQQQ/SOXL, quantum, nuclear, rare earth, AI-infra, robotics, defense \u2014 all liquidity-vetted', addedAt: '2026-08-28', route: '/chart-maps' },
  { id: 'gabbar-watch-alerts', label: '\ud83c\udfaf Gabbar level alerts \u2014 phone push when a covered name is inside or within 1% of a band (RTH, Bonde-gated, one per band per day)', addedAt: '2026-08-27', route: '/chart-maps' },
  { id: 'gex-chips-demand-tabs', label: '\ud83e\uddf2 GEX chips on the demand-zone tabs \u2014 dealer gamma helps/hurts + put/call wall sitting on your band, from the nightly snapshot', addedAt: '2026-08-27', route: '/chart-maps' },
  { id: 'ticker-chart-asof-stamp', label: 'Ticker chart: "Prices fetched Xm ago · bars through <date>" stamp — a stale snapshot can never read as live again', addedAt: '2026-08-26', route: '/chart-maps' },
  { id: 'deep-demand-cmf-rank', label: 'Deep Demand: hottest CMF on top — inflow names now rank by money-flow intensity, geometry and sales break ties', addedAt: '2026-08-26', route: '/chart-maps' },
  { id: 'gabbar-touching-only', label: 'Gabbar tab: touching-only by default — names >3% from every band are hidden and counted; untick for the full distance ladder', addedAt: '2026-08-26', route: '/chart-maps' },
  { id: 'gabbar-level-lens', label: 'Gabbar tab: Level toggle — measure the board against All / \ud83c\udfaf Aggressive / \ud83d\udee1\ufe0f Conservative 1 / Conservative 2 bands', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'gabbar-conservative-entries', label: 'Gabbar tab: 🛡️ conservative entries — deeper-band touches marked, ranked first, Conserv. stat per tile', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'gabbar-levels-tab',    label: "Gabbar Levels tab — curated bands, touching first",       addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'board-scan-stamp',     label: 'Chart Maps: scan-time + data-through stamp', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'breakouts',            label: 'Breakouts page',                      addedAt: '2026-06-16', route: '/breakouts' },
  { id: 'breakouts-columns',    label: 'Column guide on the Breakouts table', addedAt: '2026-06-17', route: '/breakouts' },
  { id: 'breakouts-beta',       label: 'Beta column + sort by low volatility', addedAt: '2026-06-17', route: '/breakouts' },
  { id: 'market-gauge-events',  label: 'FOMC & macro events on Market Gauge',  addedAt: '2026-06-17', route: '/market-gauge' },
  { id: 'page-load-monitoring', label: 'Page-load speed monitoring',           addedAt: '2026-06-18' },
  { id: 'breakouts-dynamic-scan', label: 'Update button — fast re-scan on Breakouts', addedAt: '2026-06-18', route: '/breakouts' },
  { id: 'autopilot-pnl-summary', label: 'Auto-Pilot account P&L — made/lost money since start', addedAt: '2026-06-18', route: '/trading' },
  { id: 'mvp-indicator', label: 'MVP indicator — runner vs late-stage exhaustion (Champion book)', addedAt: '2026-06-19', route: '/sepa' },
  { id: 'breakouts-buyable', label: '🎯 Buyable filter + badge on the Breakouts page', addedAt: '2026-06-19', route: '/breakouts' },
  { id: 'breakout-footprint', label: "Breakout chart: who's behind each breakout (institutional vs churn) + emerging setups", addedAt: '2026-06-21', route: '/sepa' },
  { id: 'climax-distribution', label: 'Climax-top distribution: when institutions are selling the run into retail buying', addedAt: '2026-06-21', route: '/sepa' },
  { id: 'distribution-blocks-enter', label: 'Distribution now blocks Enter — names institutions are selling are held out of the buy tier', addedAt: '2026-06-21', route: '/sepa' },
  { id: 'conviction-rank', label: '🏆 Conviction rank — lists now sort by return potential (volume + dried volume + momentum); climax runs sink', addedAt: '2026-06-22', route: '/sepa' },
  { id: 'conviction-rank-breakouts', label: '🏆 Conviction column + sort on the Breakouts board', addedAt: '2026-06-22', route: '/breakouts' },
  { id: 'cheat-tag', label: '🃏 Cheat tag — the earliest entry (TTLAC), shown in a red market when there are no breakouts', addedAt: '2026-06-22', route: '/sepa' },
  { id: 'breakouts-fresh-only', label: '🌱 Fresh only — hide extended (→R2/Past R2) names, keep the board to fresh breakouts', addedAt: '2026-06-23', route: '/breakouts' },
  { id: 'sepa-global', label: '🌍 SEPA Global — a simple, beginner-friendly version of the scanner (same Minervini rules)', addedAt: '2026-06-23', route: '/sepa-global' },
  { id: 'leveraged-badge', label: '⚠️ Leveraged-ETF flag (2x/3x) now shows on every list — they’re not Minervini stock setups', addedAt: '2026-06-23', route: '/sepa' },
  { id: 'tomorrow-bias-options', label: '🌙 Tomorrow bias — overnight/after-hours + options flow → a next-open lean on every ticker’s options-flow tab', addedAt: '2026-06-26', route: '/sepa' },
  { id: 'market-tomorrow-bias', label: '🌙 Market Tomorrow Bias — SPY/QQQ overnight gap + VIX + regime → one lean for the next session', addedAt: '2026-06-26', route: '/overnight' },
  { id: 'options-net-direction', label: '📈 Bull/Bear stock tag on the options-flow tab — plain direction next to the contrarian SOIR signal', addedAt: '2026-06-26', route: '/sepa' },
  { id: 'autopilot-analysis-column', label: '🐆 Analysis column on Auto-Pilot — the Cheetah Verdict (Minervini + Bonde) on every engine position', addedAt: '2026-06-26', route: '/trading' },
  { id: 'portfolio-buy-verdict', label: '🐆 Buy verdict on each Portfolio holding — the ENTER/WATCH/AVOID read + criteria, at a glance', addedAt: '2026-06-26', route: '/portfolio' },
  { id: 'autopilot-pnl-simple', label: '💰 Simpler Auto-Pilot P&L — started vs now total (what we gained together), realized/unrealized in the tooltip', addedAt: '2026-06-26', route: '/trading' },
  { id: 'opex-gamma-panel', label: '🧲 OpEx panel — next expiration + max-pain magnet + dealer-gamma (pin vs amplify) on the options-flow tab', addedAt: '2026-06-26', route: '/sepa' },
  { id: 'tape-order-flow', label: '🧾 Tape tab — order flow on every ticker: delta, big prints, trade flashes, volume profile + a deterministic BUY/WAIT/AVOID checklist with its own measured track record', addedAt: '2026-07-06', route: '/sepa' },
  { id: 'learning-path', label: '📚 Learning Path — your phased study plan (order flow → SMC → options vol → synthesis) with embedded videos + papers', addedAt: '2026-07-06', route: '/learning' },
  { id: 'autopilot-position-totals', label: '💵 Cost / Now / ± columns on Auto-Pilot positions + a TOTAL row summing the pluses and minuses + cash not entered', addedAt: '2026-07-06', route: '/trading' },
  { id: 'breakout-breadth', label: '🌡️ Breakout Breadth strip — breakouts/day + follow-through vs failure rate + the book\'s exposure read (sizes positions, never gates entries)', addedAt: '2026-07-10', route: '/breakouts' },
  { id: 'autopilot-rules-rs-floor', label: '📜 Auto-Pilot rules ⓘ — every rule the engine enforces, served by the engine itself; plus a new RS ≥ 80 floor (p.79 "80s or 90s") and a scan-trust gate (fresh + market-sized scans only)', addedAt: '2026-07-12', route: '/trading' },
  { id: 'autopilot-pilot-and-leaky-pivot', label: '🛫 Pilot-size entries (half size until the last 5 trades prove out, per Minervini\'s progressive exposure) + leaky-pivot suppressor (skip pivots that keep poking above and failing)', addedAt: '2026-07-12', route: '/trading' },
  { id: 'sepa-leaky-pivot', label: '🚱 Leaky pivots on the scanner — SEPA Global moves them from "Buy now" to Watch, and SEPA cards flag them, using the exact rule Auto-Pilot enforces', addedAt: '2026-07-12', route: '/sepa' },
  { id: 'autopilot-pyramiding', label: '🏗️ Pyramid adds — Auto-Pilot tops a winning position up to full size when it sets up again at a higher pivot (TTLAC "Add and Reduce"); violet auto_pyramid rows in the ledger', addedAt: '2026-07-12', route: '/trading' },
  { id: 'gex-board', label: '🧲 GEX Board — bullish vs bearish stocks by dealer gamma, each with its key nodes (flip, call/put walls, magnet) + net GEX/VEX off the options key', addedAt: '2026-07-17', route: '/gex-board' },
  { id: 'gex-setup-lens', label: '🎯 Options lens on the Setup tab — GEX + VEX best-case read per stock (does dealer hedging help or fight this setup?)', addedAt: '2026-07-17', route: '/sepa' },
  { id: 'breakouts-sort-vcp-churn', label: '🚀 Breakouts: Sort dropdown (volume options lead), 📐 VCP/setup badges on every row, and spike-and-dump days no longer count as breakouts (the GSAT fix)', addedAt: '2026-08-03', route: '/breakouts' },
  { id: 'demand-reentry-scan', label: '🟢 Back in Demand — scan the S&P 500 for names that pulled back INTO a demand zone they had left (with a Scan button), each with buy band / stop / target', addedAt: '2026-08-13', route: '/supply-demand' },
  { id: 'zone-map-setup-tab', label: '📉 Supply/demand zones drawn on every stock — red supply, green demand, with BUY band, STOP and TARGET written on the chart (Setup tab)', addedAt: '2026-08-13', route: '/sepa' },
  { id: 'quote-rule-delta', label: '🎯 Delta now classified against the real NBBO quote (Lee-Ready), not the tick-rule estimate — on CIEN the old way understated net selling by 2× (Tape tab)', addedAt: '2026-08-13', route: '/sepa' },
  { id: 'zone-map-dark-blocks', label: '🟣 Off-exchange blocks on the zone chart — every large dark print plotted at its price, flagged when it landed inside your buy band', addedAt: '2026-08-13', route: '/sepa' },
  { id: 'retail-flow', label: '🧍 Retail flow — which side retail is on, identified by sub-penny off-exchange prints and signed on the quote midpoint; ⚡ flags retail leaning against the block money', addedAt: '2026-08-14', route: '/supply-demand' },
  { id: 'sd-rr-sort-liquidity', label: '📊 Back in Demand sorted by R:R, with the win rate you\'d need to break even, daily $ volume + liquidity tier, and a dark-pool rating on every top row', addedAt: '2026-08-13', route: '/supply-demand' },
  { id: 'sd-universe-sp1500', label: '🌐 Back in Demand now scans beyond the S&P 500 — pick S&P 1500 to add ~1,000 MidCap + SmallCap names (index-quality, not a raw Russell slice)', addedAt: '2026-08-13', route: '/supply-demand' },
  { id: 'sd-knife-guard', label: '🔪 Back in Demand now filters falling knives (swing lows stepping down + falling 50-day) instead of the Minervini template — CIEN/VRT/CAT dropped off', addedAt: '2026-08-13', route: '/supply-demand' },
  { id: 'dark-pool-prints', label: '🟣 Where it printed — lit vs off-exchange (dark pool) volume split + the largest off-exchange blocks, on every ticker\'s Tape tab', addedAt: '2026-08-13', route: '/sepa' },
  { id: 'chart-maps', label: '🗺️ Chart Maps — a charts-only study board: strong VCP bases, pullbacks back into demand, and past setups from your own ledger that hit target before their stop. Every chart clicks through to the ticker.', addedAt: '2026-08-15', route: '/chart-maps' },
  { id: 'rotation-tracker', label: 'Sector Rotation — where money left and went, vs equal-weight', addedAt: '2026-08-16', route: '/rotation' },
  { id: 'zone-winners', label: '🏆 Past Winners now has a Demand zones source — 5 years of backtested zone re-entries', addedAt: '2026-08-16', route: '/chart-maps' },
  { id: 'demand-rr-floor', label: '🎯 R:R floor on Back in Demand — 36% of this board\'s backtested wins hit target on the ENTRY bar at a median 0.45R; the floor (default 1.0, adjustable, 0 = off) removes those and says how many it dropped', addedAt: '2026-08-17', route: '/supply-demand' },
  { id: 'zone-chart-fullscreen', label: '⤢ Expand the zone chart to full screen — on names like SNDK the bands sat a few pixels apart in a 340px pane; the expand button (or Esc to close) gives them the whole viewport', addedAt: '2026-08-17', route: '/sepa' },
  { id: 'chart-maps-declutter', label: '🧹 Chart Maps dropdown cleaned up — "$ turnover" is gone (it was today\'s DOLLARS, not average volume), the two volume sorts now say their unit, and AI-sector names no longer lead by default (the Themes first checkbox still does it)', addedAt: '2026-08-17', route: '/chart-maps' },
  { id: 'demand-scan-progress', label: '🔎 Live scan progress on Back in Demand — real ticker-by-ticker count, hits as they are found and an ETA, on both the Supply/Demand tab and Chart Maps (they watch the same scan)', addedAt: '2026-08-17', route: '/supply-demand' },
  { id: 'broken-band-guard', label: '🚫 A demand zone that BROKE is no longer a buy — a close below the floor drops the name (8 of 17 S&P 500 rows came off, SWKS was 18% under its band), the chart says BROKEN instead of BUY, and a stop the market already ran gets flagged', addedAt: '2026-08-17', route: '/supply-demand' },
  { id: 'chart-window', label: 'Chart window control (6m / 9m / 1y) + demand-zone charts now reach back to the touches that made the zone', addedAt: '2026-08-16', route: '/chart-maps' },
  { id: 'themes-power-energy', label: 'New rosters: AI power (IREN, CRWV) + energy, with space/quantum/semis priority', addedAt: '2026-08-16', route: '/chart-maps' },
  { id: 'chart-maps-themes', label: '⚛ Quantum / nuclear / robotics / AI-semis names now scanned — IONQ, OKLO, SMR, ARM, ALAB, CRDO and 15 more that the S&P indices structurally cannot hold', addedAt: '2026-08-15', route: '/chart-maps' },
  { id: 'chart-maps-sort-progress', label: '📊 Chart Maps: sort by retail imbalance, retail %, off-exchange %, relative volume, $ turnover, conviction or RS — ranked across the whole scan, not just the tiles on screen — plus a liquidity floor (default $10M/day, so thin names stop teaching you untradeable bases), live ticker scan progress and a Re-scan button', addedAt: '2026-08-17', route: '/chart-maps' },
  { id: 'zone-chart-candles', label: '🕯️ Zone chart rebuilt — real candlesticks + volume, and hover any day for its open / high / low / close / % change / volume. Zones now track zoom and pan (Setup tab)', addedAt: '2026-08-16', route: '/sepa' },
  { id: 'symbol-renames', label: '↪️ Renamed tickers now follow the company — SATS reads as ECHO and SQ as XYZ, with history joined across the change (SQ had been showing dead for 576 days)', addedAt: '2026-08-16', route: '/sepa' },
  { id: 'rotation-backtest', label: '🧪 Sector Rotation now shows whether acting on it pays — 116 monthly rebalances back to 2016: buying the top 3 sectors LOST to just holding all 11', addedAt: '2026-08-16', route: '/rotation' },
  { id: 'chart-maps-earnings-flow', label: '📊 Earnings Flow tab on Chart Maps — today\u2019s reports that institutions BOUGHT (big volume, closing near the high, $50M+ traded), plus names reporting after today\u2019s close that they\u2019re already accumulating into. TGT closed +4.3% after gapping down 3%; BULL ran +8.9% on 3.1x into tonight\u2019s print', addedAt: '2026-08-19', route: '/chart-maps' },
  { id: 'demand-track-record', label: '📒 Back in Demand now keeps its own history — every board is recorded, each name graded at the next open against the plan frozen when it first appeared, with excess-vs-SPY and a day-by-day entered/dropped log. Not the backtest: this is what the page actually said', addedAt: '2026-08-17', route: '/supply-demand' },
  { id: 'zonechart-plan-labels', label: '🏷️ Zone chart labels moved off the candles — BUY / STOP / TARGET / NOW now sit in blank space to the right, spread apart so they stop covering each other, with TARGET in its own colour and the duplicate price chip removed', addedAt: '2026-08-18', route: '/supply-demand' },
  { id: 'chart-maps-into-supply', label: '\uD83D\uDEA7 Into Supply tab on Chart Maps \u2014 the inverse of Back in Demand: names that have rallied INTO a tested ceiling, or sit within 3% under one, with the next support underneath and a room-up:down ratio. Under 1.00 means more air below than above. Rides the same scan, so it costs a page load not a second pass', addedAt: '2026-08-24', route: '/chart-maps' },
  { id: 'chart-hover-readout', label: '\uD83C\uDFAF Hover any Chart Maps chart \u2014 a crosshair reads the exact $ at your cursor, the bar\u2019s date + OHLC + volume, and names the band you are standing in. Also fixes the clipped right-edge labels (META was showing \"overhead 553\" and \"support 527.\") \u2014 the gutter now sizes itself to whatever it has to hold', addedAt: '2026-08-24', route: '/chart-maps' },
  { id: 'chart-price-axis', label: '\uD83D\uDCC8 Price scale on every Chart Maps chart \u2014 gridlines with the actual $ numbers down the right side, so you can read what price a demand band sits at without opening the table. BUY / STOP / TARGET / NOW still win the label where they overlap, since those are more precise than the round tick next to them', addedAt: '2026-08-24', route: '/chart-maps' },
  { id: 'chart-maps-support-levels', label: '\uD83D\uDCCF Support Levels tab on Chart Maps \u2014 search any ticker and toggle the zoom between 1 month / 3 months / 6 months / 1 year. The same rule reads a different frame, so the answers differ on purpose: a short read finds the level this week\u2019s trade is standing on, a long one the structural floor. Levels tested inside the last month are marked, and the nearest overhead is shown next to the support so you can see the ceiling before you buy the floor', addedAt: '2026-08-24', route: '/chart-maps' },
  { id: 'chart-maps-zero-dte', label: '\u26A1 0DTE tab on Chart Maps \u2014 same-day expiry calls and puts across 13 names that actually have dailies. Each row names a strike and says how much of TODAY\u2019S expected move it needs to double (\u201C0.19x\u201D), which is the only figure comparable across names \u2014 SPY needed 0.06% and TSLA 0.94% for the same trade. A badge says whether dealers are PINNING (suppressing the move, working against you) or AMPLIFYING it, and greys out when that reading is too close to call. Theta is shown as a share of the whole premium because on 0DTE it routinely exceeds it \u2014 SPY\u2019s own suggestion was burning 787%/day. Nothing here is backtested (there is no intraday option history to backtest against), so every suggestion is recorded and graded from day one', addedAt: '2026-08-24', route: '/chart-maps' },
  { id: 'intraday-ema-bigdelta', label: '\u26A1 9/21 EMA lines on the live chart + Big Delta per candle on the Tape tab \u2014 the amber line is the 9-EMA, blue is the 21, drawn on both the 1m and daily views and ticking live with the price. On the Tape tab, under the cumulative delta line, green/red bars now show who won EACH minute \u2014 a level being defended shows as green bars printing into red tape, which the running total smooths away. First slice of the intraday order-flow stack; live prints and Trade Flash alerts are next', addedAt: '2026-08-24', route: '/sepa' },
  { id: 'trade-flash', label: '\u26A1 Trade Flash \u2014 when a big one-sided burst ($250k+, 75%+ one side, inside 10 seconds) prints AT one of your demand or supply zones, it now hits your phone and shows on the Supply & Demand page. Location gates the alert: the same burst mid-range is ignored, and the wording tells you what it means \u2014 \u201Cbuyers stepping in at the zone\u201D vs \u201Csellers defending the ceiling\u201D. Zone tiles on Chart Maps get a \u26A1 badge the same day. Auction crosses are excluded (AVGO printed $1.09B at the 9:30 bell \u2014 that is the auction, not a buyer)', addedAt: '2026-08-24', route: '/supply-demand' },
  { id: 'zone-overlay', label: '\uD83D\uDCD0 All-windows overlay on Support Levels \u2014 pick \u201CAll windows \u00B7 overlay\u201D in the zoom dropdown and every timeframe\u2019s zones (1m/3m/6m/1y) are computed independently and clustered: levels that 2+ windows agree on are drawn, each labelled with how many zooms see it. Agreement is the signal \u2014 a level only one zoom can see is usually an artifact of that zoom. Strength is deliberately not shown (it does not compare across windows); touch counts keep the longest window\u2019s honest count', addedAt: '2026-08-25', route: '/chart-maps' },
  { id: 'russell-watch', label: '\uD83E\uDDFA Russell Watch tab on Catalysts \u2014 names sized to be ADDED to the Russell 2000 at the 2026-09-21 reconstitution (index funds must buy; EMAT was exactly this trade) and R2000 names sized for promotion to the R1000 (usually net tracker SELLING \u2014 the table says so). Cap-screen approximation vs current member bands, with its baseline date and limits printed on the page', addedAt: '2026-09-01', route: '/chart-maps?tab=catalysts' },
  { id: 'overnight-tab-chart-maps', label: '\uD83C\uDF19 Overnight tab on Chart Maps \u2014 the overnight movers scan where the rest of your boards live, with three honesty fixes: the O/N chip now only marks a move that actually happened in extended hours (SNDK read \u201C+4.4% O/N\u201D on a night it drifted \u22121.1% after hours \u2014 that was Monday\u2019s session), a new O/N drift column shows the real after-hours change, and \u201C$ Vol avg\u201D is labelled as the 50-day average it always was \u2014 with a new O/N $ Vol column showing the dollars that ACTUALLY traded tonight. Click a row to drill into Support Levels', addedAt: '2026-09-01', route: '/chart-maps?tab=overnight' },
  { id: 'signal-lab', label: '\u26A1 Signal Lab \u2014 add YOUR tickers and get BUY / SELL tags printed on live 1-minute candles, GainzAlgo-style: the opening range, liquidity sweeps and BOS/CHoCH structure composed into the five-step entry, each signal with its stop (the trap wick) and 2R target. Closed bars only \u2014 signals never repaint (that claim is enforced by a test, not marketing). Refreshes every 45s while the session is on; your list follows you across browsers', addedAt: '2026-09-01', route: '/signal-lab' },
  { id: 'chart-overlay-legend', label: '\u2611\uFE0F Chart legend with checkboxes \u2014 every chart (Chart Maps tiles, Support tab, Session tab) now carries a ledger naming each overlay family with its colour, and unchecking one hides it everywhere: demand/supply bands, order blocks, FVGs, ranges, BUY/STOP/TARGET lines, the swept/BOS/CHoCH labels and the now marker each get their own box. Your picks stick across visits. Plus a TV \u2197 button on every chart that opens the symbol pre-configured in TradingView at the right interval', addedAt: '2026-08-31', route: '/chart-maps' },
  { id: 'setup-tab-direct', label: '🎯 Chart Maps zone tiles and Back in Demand rows now open straight on the Setup tab — the plan, not the chart you were already looking at', addedAt: '2026-08-17', route: '/supply-demand' },
];

/** A feature stops highlighting this many days after it shipped. */
export const NEW_WINDOW_DAYS = 30;

/** True if `addedAt` is within the highlight window relative to `now`. */
export function isRecent(addedAt: string, now: Date, days = NEW_WINDOW_DAYS): boolean {
  const t = Date.parse(`${addedAt}T00:00:00`);
  if (Number.isNaN(t)) return false;
  const age = now.getTime() - t;
  return age >= -86_400_000 && age <= days * 86_400_000;   // shipped (≤1d future tol) & recent
}
