/**
 * politicalDisclosures.contract.test.ts — the TS is GENERATED, and this is the
 * proof.
 *
 * Ajay 2026-09-20 asked for the 🏛️ watch. A cron container cannot read
 * TypeScript, so the curated list moved to backend/political/disclosures.json
 * and backend/scripts/gen_political_ts.py writes this module from it. Two
 * copies of a curated list is two copies that drift — this file fails the
 * moment they do.
 *
 * The backend side of the same contract lives in
 * backend/tests/test_political_disclosures.py (`--check` on the generator).
 * This side asserts the shipped TS equals the shipped JSON row for row, so a
 * hand edit to either one goes red here without running Python.
 */
import { describe, it, expect } from 'vitest';
import {
  POLITICAL_DISCLOSURES,
  POLITICAL_DISCLOSURE_TOTAL_COUNT,
  POLITICAL_DISCLOSURE_SOURCE_NOTE,
  getPoliticalDisclosure,
  type DisclosureEntry,
} from './politicalDisclosures';
import generated from './politicalDisclosures.generated.json';

const rows = generated as unknown as DisclosureEntry[];

describe('the shipped TS is the shipped JSON', () => {
  it('carries the same number of rows', () => {
    expect(POLITICAL_DISCLOSURES.length).toBe(rows.length);
    expect(POLITICAL_DISCLOSURE_TOTAL_COUNT).toBe(rows.length);
    expect(rows.length).toBe(44);
  });

  it('matches row for row, in order, on every field', () => {
    POLITICAL_DISCLOSURES.forEach((e, i) => {
      const j = rows[i];
      expect(e.ticker, `row ${i} ticker`).toBe(j.ticker);
      expect(e.company, `${j.ticker} company`).toBe(j.company);
      expect(e.sector, `${j.ticker} sector`).toBe(j.sector);
      expect(e.categories, `${j.ticker} categories`).toEqual(j.categories);
      expect(e.disclosureBand ?? null, `${j.ticker} band`).toBe(j.disclosureBand ?? null);
      expect(e.govtStake ?? null, `${j.ticker} govtStake`).toBe(j.govtStake ?? null);
      expect(e.notes ?? null, `${j.ticker} notes`).toBe(j.notes ?? null);
      expect(e.asOf ?? null, `${j.ticker} asOf`).toBe(j.asOf ?? null);
      expect(e.addedOn ?? null, `${j.ticker} addedOn`).toBe(j.addedOn ?? null);
    });
  });

  it('resolves every JSON ticker through the lookup', () => {
    for (const j of rows) {
      expect(getPoliticalDisclosure(j.ticker), j.ticker).not.toBeNull();
    }
  });

  // ── negatives ────────────────────────────────────────────────────────────
  it('a ticker that is NOT in the JSON resolves to null', () => {
    const known = new Set(rows.map((r) => r.ticker));
    expect(known.has('ZZZZ')).toBe(false);
    expect(getPoliticalDisclosure('ZZZZ')).toBeNull();
  });

  it('no row claims a government stake without a named agency and a size', () => {
    for (const j of rows) {
      if (!j.govtStake) continue;
      expect(j.categories, `${j.ticker}`).toContain('govt_investment');
      expect(j.govtStake, `${j.ticker}`).toMatch(/\d+(\.\d+)?%/);
      expect(j.govtStake!.replace(/[\d%.\s]/g, '').length, `${j.ticker}`).toBeGreaterThan(2);
    }
  });

  it('the Greenland cohort still claims nothing', () => {
    for (const t of ['GLND', 'CRML', 'UUUU']) {
      const j = rows.find((r) => r.ticker === t)!;
      expect(j.categories, t).toEqual(['inferred']);
      expect(j.govtStake ?? null, t).toBeNull();
    }
  });
});

describe('the file says where it comes from', () => {
  it('the source note names the JSON and the generator, not this file', () => {
    expect(POLITICAL_DISCLOSURE_SOURCE_NOTE).toContain('backend/political/disclosures.json');
    expect(POLITICAL_DISCLOSURE_SOURCE_NOTE).toContain('gen_political_ts.py');
    expect(POLITICAL_DISCLOSURE_SOURCE_NOTE).not.toContain('Edit src/lib/politicalDisclosures.ts');
  });

  it('the header marks the module GENERATED — DO NOT EDIT', async () => {
    const raw = (await import('./politicalDisclosures.ts?raw')).default as string;
    expect(raw).toContain('GENERATED by backend/scripts/gen_political_ts.py');
    expect(raw).toContain('DO NOT EDIT');
  });
});
